/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/kzz45/neverdown/pkg/client-go/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Affinities returns a AffinityInformer.
	Affinities() AffinityInformer
	// AliyunAccessControls returns a AliyunAccessControlInformer.
	AliyunAccessControls() AliyunAccessControlInformer
	// AliyunLoadBalancers returns a AliyunLoadBalancerInformer.
	AliyunLoadBalancers() AliyunLoadBalancerInformer
	// Etcds returns a EtcdInformer.
	Etcds() EtcdInformer
	// Mysqls returns a MysqlInformer.
	Mysqls() MysqlInformer
	// NodeSelectors returns a NodeSelectorInformer.
	NodeSelectors() NodeSelectorInformer
	// Openxes returns a OpenxInformer.
	Openxes() OpenxInformer
	// Redises returns a RedisInformer.
	Redises() RedisInformer
	// Tolerations returns a TolerationInformer.
	Tolerations() TolerationInformer
	// VolcAccessControls returns a VolcAccessControlInformer.
	VolcAccessControls() VolcAccessControlInformer
	// VolcLoadBalancers returns a VolcLoadBalancerInformer.
	VolcLoadBalancers() VolcLoadBalancerInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Affinities returns a AffinityInformer.
func (v *version) Affinities() AffinityInformer {
	return &affinityInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AliyunAccessControls returns a AliyunAccessControlInformer.
func (v *version) AliyunAccessControls() AliyunAccessControlInformer {
	return &aliyunAccessControlInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AliyunLoadBalancers returns a AliyunLoadBalancerInformer.
func (v *version) AliyunLoadBalancers() AliyunLoadBalancerInformer {
	return &aliyunLoadBalancerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Etcds returns a EtcdInformer.
func (v *version) Etcds() EtcdInformer {
	return &etcdInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Mysqls returns a MysqlInformer.
func (v *version) Mysqls() MysqlInformer {
	return &mysqlInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// NodeSelectors returns a NodeSelectorInformer.
func (v *version) NodeSelectors() NodeSelectorInformer {
	return &nodeSelectorInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Openxes returns a OpenxInformer.
func (v *version) Openxes() OpenxInformer {
	return &openxInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Redises returns a RedisInformer.
func (v *version) Redises() RedisInformer {
	return &redisInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Tolerations returns a TolerationInformer.
func (v *version) Tolerations() TolerationInformer {
	return &tolerationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VolcAccessControls returns a VolcAccessControlInformer.
func (v *version) VolcAccessControls() VolcAccessControlInformer {
	return &volcAccessControlInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VolcLoadBalancers returns a VolcLoadBalancerInformer.
func (v *version) VolcLoadBalancers() VolcLoadBalancerInformer {
	return &volcLoadBalancerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
