/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/kzz45/neverdown/pkg/apis/openx/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolcAccessControls implements VolcAccessControlInterface
type FakeVolcAccessControls struct {
	Fake *FakeOpenxV1
	ns   string
}

var volcaccesscontrolsResource = v1.SchemeGroupVersion.WithResource("volcaccesscontrols")

var volcaccesscontrolsKind = v1.SchemeGroupVersion.WithKind("VolcAccessControl")

// Get takes name of the volcAccessControl, and returns the corresponding volcAccessControl object, and an error if there is any.
func (c *FakeVolcAccessControls) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.VolcAccessControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(volcaccesscontrolsResource, c.ns, name), &v1.VolcAccessControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VolcAccessControl), err
}

// List takes label and field selectors, and returns the list of VolcAccessControls that match those selectors.
func (c *FakeVolcAccessControls) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VolcAccessControlList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(volcaccesscontrolsResource, volcaccesscontrolsKind, c.ns, opts), &v1.VolcAccessControlList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.VolcAccessControlList{ListMeta: obj.(*v1.VolcAccessControlList).ListMeta}
	for _, item := range obj.(*v1.VolcAccessControlList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volcAccessControls.
func (c *FakeVolcAccessControls) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(volcaccesscontrolsResource, c.ns, opts))

}

// Create takes the representation of a volcAccessControl and creates it.  Returns the server's representation of the volcAccessControl, and an error, if there is any.
func (c *FakeVolcAccessControls) Create(ctx context.Context, volcAccessControl *v1.VolcAccessControl, opts metav1.CreateOptions) (result *v1.VolcAccessControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(volcaccesscontrolsResource, c.ns, volcAccessControl), &v1.VolcAccessControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VolcAccessControl), err
}

// Update takes the representation of a volcAccessControl and updates it. Returns the server's representation of the volcAccessControl, and an error, if there is any.
func (c *FakeVolcAccessControls) Update(ctx context.Context, volcAccessControl *v1.VolcAccessControl, opts metav1.UpdateOptions) (result *v1.VolcAccessControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(volcaccesscontrolsResource, c.ns, volcAccessControl), &v1.VolcAccessControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VolcAccessControl), err
}

// Delete takes name of the volcAccessControl and deletes it. Returns an error if one occurs.
func (c *FakeVolcAccessControls) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(volcaccesscontrolsResource, c.ns, name, opts), &v1.VolcAccessControl{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolcAccessControls) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(volcaccesscontrolsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.VolcAccessControlList{})
	return err
}

// Patch applies the patch and returns the patched volcAccessControl.
func (c *FakeVolcAccessControls) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VolcAccessControl, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(volcaccesscontrolsResource, c.ns, name, pt, data, subresources...), &v1.VolcAccessControl{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VolcAccessControl), err
}
