/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/kzz45/neverdown/pkg/apis/openx/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOpenxes implements OpenxInterface
type FakeOpenxes struct {
	Fake *FakeOpenxV1
	ns   string
}

var openxesResource = v1.SchemeGroupVersion.WithResource("openxes")

var openxesKind = v1.SchemeGroupVersion.WithKind("Openx")

// Get takes name of the openx, and returns the corresponding openx object, and an error if there is any.
func (c *FakeOpenxes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Openx, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(openxesResource, c.ns, name), &v1.Openx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Openx), err
}

// List takes label and field selectors, and returns the list of Openxes that match those selectors.
func (c *FakeOpenxes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.OpenxList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(openxesResource, openxesKind, c.ns, opts), &v1.OpenxList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.OpenxList{ListMeta: obj.(*v1.OpenxList).ListMeta}
	for _, item := range obj.(*v1.OpenxList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested openxes.
func (c *FakeOpenxes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(openxesResource, c.ns, opts))

}

// Create takes the representation of a openx and creates it.  Returns the server's representation of the openx, and an error, if there is any.
func (c *FakeOpenxes) Create(ctx context.Context, openx *v1.Openx, opts metav1.CreateOptions) (result *v1.Openx, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(openxesResource, c.ns, openx), &v1.Openx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Openx), err
}

// Update takes the representation of a openx and updates it. Returns the server's representation of the openx, and an error, if there is any.
func (c *FakeOpenxes) Update(ctx context.Context, openx *v1.Openx, opts metav1.UpdateOptions) (result *v1.Openx, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(openxesResource, c.ns, openx), &v1.Openx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Openx), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOpenxes) UpdateStatus(ctx context.Context, openx *v1.Openx, opts metav1.UpdateOptions) (*v1.Openx, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(openxesResource, "status", c.ns, openx), &v1.Openx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Openx), err
}

// Delete takes name of the openx and deletes it. Returns an error if one occurs.
func (c *FakeOpenxes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(openxesResource, c.ns, name, opts), &v1.Openx{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOpenxes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(openxesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.OpenxList{})
	return err
}

// Patch applies the patch and returns the patched openx.
func (c *FakeOpenxes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Openx, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(openxesResource, c.ns, name, pt, data, subresources...), &v1.Openx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Openx), err
}
