/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/kzz45/neverdown/pkg/apis/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRbacServiceAccounts implements RbacServiceAccountInterface
type FakeRbacServiceAccounts struct {
	Fake *FakeRbacV1
	ns   string
}

var rbacserviceaccountsResource = v1.SchemeGroupVersion.WithResource("rbacserviceaccounts")

var rbacserviceaccountsKind = v1.SchemeGroupVersion.WithKind("RbacServiceAccount")

// Get takes name of the rbacServiceAccount, and returns the corresponding rbacServiceAccount object, and an error if there is any.
func (c *FakeRbacServiceAccounts) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RbacServiceAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rbacserviceaccountsResource, c.ns, name), &v1.RbacServiceAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RbacServiceAccount), err
}

// List takes label and field selectors, and returns the list of RbacServiceAccounts that match those selectors.
func (c *FakeRbacServiceAccounts) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RbacServiceAccountList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rbacserviceaccountsResource, rbacserviceaccountsKind, c.ns, opts), &v1.RbacServiceAccountList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.RbacServiceAccountList{ListMeta: obj.(*v1.RbacServiceAccountList).ListMeta}
	for _, item := range obj.(*v1.RbacServiceAccountList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rbacServiceAccounts.
func (c *FakeRbacServiceAccounts) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rbacserviceaccountsResource, c.ns, opts))

}

// Create takes the representation of a rbacServiceAccount and creates it.  Returns the server's representation of the rbacServiceAccount, and an error, if there is any.
func (c *FakeRbacServiceAccounts) Create(ctx context.Context, rbacServiceAccount *v1.RbacServiceAccount, opts metav1.CreateOptions) (result *v1.RbacServiceAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rbacserviceaccountsResource, c.ns, rbacServiceAccount), &v1.RbacServiceAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RbacServiceAccount), err
}

// Update takes the representation of a rbacServiceAccount and updates it. Returns the server's representation of the rbacServiceAccount, and an error, if there is any.
func (c *FakeRbacServiceAccounts) Update(ctx context.Context, rbacServiceAccount *v1.RbacServiceAccount, opts metav1.UpdateOptions) (result *v1.RbacServiceAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rbacserviceaccountsResource, c.ns, rbacServiceAccount), &v1.RbacServiceAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RbacServiceAccount), err
}

// Delete takes name of the rbacServiceAccount and deletes it. Returns an error if one occurs.
func (c *FakeRbacServiceAccounts) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(rbacserviceaccountsResource, c.ns, name, opts), &v1.RbacServiceAccount{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRbacServiceAccounts) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rbacserviceaccountsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.RbacServiceAccountList{})
	return err
}

// Patch applies the patch and returns the patched rbacServiceAccount.
func (c *FakeRbacServiceAccounts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RbacServiceAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rbacserviceaccountsResource, c.ns, name, pt, data, subresources...), &v1.RbacServiceAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RbacServiceAccount), err
}
