/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/kzz45/neverdown/pkg/apis/openx/v1"
	scheme "github.com/kzz45/neverdown/pkg/client-go/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AccessControlsGetter has a method to return a AccessControlInterface.
// A group's client should implement this interface.
type AccessControlsGetter interface {
	AccessControls(namespace string) AccessControlInterface
}

// AccessControlInterface has methods to work with AccessControl resources.
type AccessControlInterface interface {
	Create(ctx context.Context, accessControl *v1.AccessControl, opts metav1.CreateOptions) (*v1.AccessControl, error)
	Update(ctx context.Context, accessControl *v1.AccessControl, opts metav1.UpdateOptions) (*v1.AccessControl, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AccessControl, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AccessControlList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AccessControl, err error)
	AccessControlExpansion
}

// accessControls implements AccessControlInterface
type accessControls struct {
	client rest.Interface
	ns     string
}

// newAccessControls returns a AccessControls
func newAccessControls(c *OpenxV1Client, namespace string) *accessControls {
	return &accessControls{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the accessControl, and returns the corresponding accessControl object, and an error if there is any.
func (c *accessControls) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AccessControl, err error) {
	result = &v1.AccessControl{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("accesscontrols").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AccessControls that match those selectors.
func (c *accessControls) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AccessControlList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AccessControlList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("accesscontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested accessControls.
func (c *accessControls) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("accesscontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a accessControl and creates it.  Returns the server's representation of the accessControl, and an error, if there is any.
func (c *accessControls) Create(ctx context.Context, accessControl *v1.AccessControl, opts metav1.CreateOptions) (result *v1.AccessControl, err error) {
	result = &v1.AccessControl{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("accesscontrols").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accessControl).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a accessControl and updates it. Returns the server's representation of the accessControl, and an error, if there is any.
func (c *accessControls) Update(ctx context.Context, accessControl *v1.AccessControl, opts metav1.UpdateOptions) (result *v1.AccessControl, err error) {
	result = &v1.AccessControl{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("accesscontrols").
		Name(accessControl.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accessControl).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the accessControl and deletes it. Returns an error if one occurs.
func (c *accessControls) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("accesscontrols").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *accessControls) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("accesscontrols").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched accessControl.
func (c *accessControls) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AccessControl, err error) {
	result = &v1.AccessControl{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("accesscontrols").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
