/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/kzz45/neverdown/pkg/apis/openx/v1"
	scheme "github.com/kzz45/neverdown/pkg/client-go/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AliyunLoadBalancersGetter has a method to return a AliyunLoadBalancerInterface.
// A group's client should implement this interface.
type AliyunLoadBalancersGetter interface {
	AliyunLoadBalancers(namespace string) AliyunLoadBalancerInterface
}

// AliyunLoadBalancerInterface has methods to work with AliyunLoadBalancer resources.
type AliyunLoadBalancerInterface interface {
	Create(ctx context.Context, aliyunLoadBalancer *v1.AliyunLoadBalancer, opts metav1.CreateOptions) (*v1.AliyunLoadBalancer, error)
	Update(ctx context.Context, aliyunLoadBalancer *v1.AliyunLoadBalancer, opts metav1.UpdateOptions) (*v1.AliyunLoadBalancer, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AliyunLoadBalancer, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AliyunLoadBalancerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AliyunLoadBalancer, err error)
	AliyunLoadBalancerExpansion
}

// aliyunLoadBalancers implements AliyunLoadBalancerInterface
type aliyunLoadBalancers struct {
	client rest.Interface
	ns     string
}

// newAliyunLoadBalancers returns a AliyunLoadBalancers
func newAliyunLoadBalancers(c *OpenxV1Client, namespace string) *aliyunLoadBalancers {
	return &aliyunLoadBalancers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aliyunLoadBalancer, and returns the corresponding aliyunLoadBalancer object, and an error if there is any.
func (c *aliyunLoadBalancers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AliyunLoadBalancer, err error) {
	result = &v1.AliyunLoadBalancer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("aliyunloadbalancers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AliyunLoadBalancers that match those selectors.
func (c *aliyunLoadBalancers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AliyunLoadBalancerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AliyunLoadBalancerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("aliyunloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aliyunLoadBalancers.
func (c *aliyunLoadBalancers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("aliyunloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aliyunLoadBalancer and creates it.  Returns the server's representation of the aliyunLoadBalancer, and an error, if there is any.
func (c *aliyunLoadBalancers) Create(ctx context.Context, aliyunLoadBalancer *v1.AliyunLoadBalancer, opts metav1.CreateOptions) (result *v1.AliyunLoadBalancer, err error) {
	result = &v1.AliyunLoadBalancer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("aliyunloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aliyunLoadBalancer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aliyunLoadBalancer and updates it. Returns the server's representation of the aliyunLoadBalancer, and an error, if there is any.
func (c *aliyunLoadBalancers) Update(ctx context.Context, aliyunLoadBalancer *v1.AliyunLoadBalancer, opts metav1.UpdateOptions) (result *v1.AliyunLoadBalancer, err error) {
	result = &v1.AliyunLoadBalancer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("aliyunloadbalancers").
		Name(aliyunLoadBalancer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aliyunLoadBalancer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aliyunLoadBalancer and deletes it. Returns an error if one occurs.
func (c *aliyunLoadBalancers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("aliyunloadbalancers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aliyunLoadBalancers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("aliyunloadbalancers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aliyunLoadBalancer.
func (c *aliyunLoadBalancers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AliyunLoadBalancer, err error) {
	result = &v1.AliyunLoadBalancer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("aliyunloadbalancers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
