// Protocol for AuthxApi.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.3
// source: pkg/authx/grpc/proto/api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname *string `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname *string `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

type AppMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     *string `protobuf:"bytes,1,req,name=appId" json:"appId,omitempty"`
	AppSecret *string `protobuf:"bytes,2,req,name=appSecret" json:"appSecret,omitempty"`
}

func (x *AppMeta) Reset() {
	*x = AppMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMeta) ProtoMessage() {}

func (x *AppMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMeta.ProtoReflect.Descriptor instead.
func (*AppMeta) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *AppMeta) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *AppMeta) GetAppSecret() string {
	if x != nil && x.AppSecret != nil {
		return *x.AppSecret
	}
	return ""
}

type AccountMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Nickname *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	Password *string `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	Email    *string `protobuf:"bytes,4,req,name=email" json:"email,omitempty"`
}

func (x *AccountMeta) Reset() {
	*x = AccountMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMeta) ProtoMessage() {}

func (x *AccountMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMeta.ProtoReflect.Descriptor instead.
func (*AccountMeta) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *AccountMeta) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *AccountMeta) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *AccountMeta) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *AccountMeta) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type ClusterRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppMeta     *AppMeta     `protobuf:"bytes,1,req,name=appMeta" json:"appMeta,omitempty"`
	AccountMeta *AccountMeta `protobuf:"bytes,2,req,name=accountMeta" json:"accountMeta,omitempty"`
}

func (x *ClusterRoleRequest) Reset() {
	*x = ClusterRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRoleRequest) ProtoMessage() {}

func (x *ClusterRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRoleRequest.ProtoReflect.Descriptor instead.
func (*ClusterRoleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterRoleRequest) GetAppMeta() *AppMeta {
	if x != nil {
		return x.AppMeta
	}
	return nil
}

func (x *ClusterRoleRequest) GetAccountMeta() *AccountMeta {
	if x != nil {
		return x.AccountMeta
	}
	return nil
}

type StandardReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Reason  *string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
}

func (x *StandardReply) Reset() {
	*x = StandardReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardReply) ProtoMessage() {}

func (x *StandardReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardReply.ProtoReflect.Descriptor instead.
func (*StandardReply) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *StandardReply) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *StandardReply) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type ClusterRoleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *StandardReply `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	Role   []byte         `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
}

func (x *ClusterRoleReply) Reset() {
	*x = ClusterRoleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRoleReply) ProtoMessage() {}

func (x *ClusterRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRoleReply.ProtoReflect.Descriptor instead.
func (*ClusterRoleReply) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterRoleReply) GetResult() *StandardReply {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ClusterRoleReply) GetRole() []byte {
	if x != nil {
		return x.Role
	}
	return nil
}

type GroupVersionKind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group   *string `protobuf:"bytes,1,req,name=group" json:"group,omitempty"`
	Version *string `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	Kind    *string `protobuf:"bytes,3,req,name=kind" json:"kind,omitempty"`
}

func (x *GroupVersionKind) Reset() {
	*x = GroupVersionKind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupVersionKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupVersionKind) ProtoMessage() {}

func (x *GroupVersionKind) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupVersionKind.ProtoReflect.Descriptor instead.
func (*GroupVersionKind) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *GroupVersionKind) GetGroup() string {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return ""
}

func (x *GroupVersionKind) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *GroupVersionKind) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace        *string           `protobuf:"bytes,1,req,name=namespace" json:"namespace,omitempty"`
	GroupVersionKind *GroupVersionKind `protobuf:"bytes,2,req,name=groupVersionKind" json:"groupVersionKind,omitempty"`
	Verb             *string           `protobuf:"bytes,3,req,name=verb" json:"verb,omitempty"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *Rule) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *Rule) GetGroupVersionKind() *GroupVersionKind {
	if x != nil {
		return x.GroupVersionKind
	}
	return nil
}

func (x *Rule) GetVerb() string {
	if x != nil && x.Verb != nil {
		return *x.Verb
	}
	return ""
}

type ValidateRuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppMeta     *AppMeta     `protobuf:"bytes,1,req,name=appMeta" json:"appMeta,omitempty"`
	AccountMeta *AccountMeta `protobuf:"bytes,2,req,name=accountMeta" json:"accountMeta,omitempty"`
	Rule        *Rule        `protobuf:"bytes,3,req,name=rule" json:"rule,omitempty"`
}

func (x *ValidateRuleRequest) Reset() {
	*x = ValidateRuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleRequest) ProtoMessage() {}

func (x *ValidateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleRequest.ProtoReflect.Descriptor instead.
func (*ValidateRuleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateRuleRequest) GetAppMeta() *AppMeta {
	if x != nil {
		return x.AppMeta
	}
	return nil
}

func (x *ValidateRuleRequest) GetAccountMeta() *AccountMeta {
	if x != nil {
		return x.AccountMeta
	}
	return nil
}

func (x *ValidateRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ValidateRuleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *StandardReply `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	Root   *bool          `protobuf:"varint,2,opt,name=root" json:"root,omitempty"`
}

func (x *ValidateRuleReply) Reset() {
	*x = ValidateRuleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateRuleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRuleReply) ProtoMessage() {}

func (x *ValidateRuleReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRuleReply.ProtoReflect.Descriptor instead.
func (*ValidateRuleReply) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateRuleReply) GetResult() *StandardReply {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ValidateRuleReply) GetRoot() bool {
	if x != nil && x.Root != nil {
		return *x.Root
	}
	return false
}

type RegisterRuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppMeta                  *AppMeta     `protobuf:"bytes,1,req,name=appMeta" json:"appMeta,omitempty"`
	AccountMeta              *AccountMeta `protobuf:"bytes,2,req,name=accountMeta" json:"accountMeta,omitempty"`
	GroupVersionKindRuleList []byte       `protobuf:"bytes,3,req,name=groupVersionKindRuleList" json:"groupVersionKindRuleList,omitempty"`
}

func (x *RegisterRuleRequest) Reset() {
	*x = RegisterRuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRuleRequest) ProtoMessage() {}

func (x *RegisterRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRuleRequest.ProtoReflect.Descriptor instead.
func (*RegisterRuleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRuleRequest) GetAppMeta() *AppMeta {
	if x != nil {
		return x.AppMeta
	}
	return nil
}

func (x *RegisterRuleRequest) GetAccountMeta() *AccountMeta {
	if x != nil {
		return x.AccountMeta
	}
	return nil
}

func (x *RegisterRuleRequest) GetGroupVersionKindRuleList() []byte {
	if x != nil {
		return x.GroupVersionKindRuleList
	}
	return nil
}

type RegisterRuleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *StandardReply `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
}

func (x *RegisterRuleReply) Reset() {
	*x = RegisterRuleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRuleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRuleReply) ProtoMessage() {}

func (x *RegisterRuleReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_authx_grpc_proto_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRuleReply.ProtoReflect.Descriptor instead.
func (*RegisterRuleReply) Descriptor() ([]byte, []int) {
	return file_pkg_authx_grpc_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterRuleReply) GetResult() *StandardReply {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_pkg_authx_grpc_proto_api_proto protoreflect.FileDescriptor

var file_pkg_authx_grpc_proto_api_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x78, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x22, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x04,
	0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x3d, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22,
	0x77, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x76, 0x0a, 0x12, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x07, 0x61, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x22, 0x41, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x10, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x56, 0x0a, 0x10, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x22, 0x7e, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x10, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x65, 0x72, 0x62, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x76, 0x65,
	0x72, 0x62, 0x22, 0x99, 0x01, 0x0a, 0x13, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x61, 0x70,
	0x70, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x04,
	0x72, 0x75, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x22, 0x56,
	0x0a, 0x11, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x22, 0xb3, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x07, 0x61, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x3a, 0x0a, 0x18, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x0c, 0x52, 0x18, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x11,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x90, 0x02, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x78, 0x41, 0x70, 0x69, 0x12, 0x29, 0x0a,
	0x09, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x0c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x1a, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_pkg_authx_grpc_proto_api_proto_rawDescOnce sync.Once
	file_pkg_authx_grpc_proto_api_proto_rawDescData = file_pkg_authx_grpc_proto_api_proto_rawDesc
)

func file_pkg_authx_grpc_proto_api_proto_rawDescGZIP() []byte {
	file_pkg_authx_grpc_proto_api_proto_rawDescOnce.Do(func() {
		file_pkg_authx_grpc_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_authx_grpc_proto_api_proto_rawDescData)
	})
	return file_pkg_authx_grpc_proto_api_proto_rawDescData
}

var file_pkg_authx_grpc_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_authx_grpc_proto_api_proto_goTypes = []interface{}{
	(*Ping)(nil),                // 0: api.v1.Ping
	(*Pong)(nil),                // 1: api.v1.Pong
	(*AppMeta)(nil),             // 2: api.v1.AppMeta
	(*AccountMeta)(nil),         // 3: api.v1.AccountMeta
	(*ClusterRoleRequest)(nil),  // 4: api.v1.ClusterRoleRequest
	(*StandardReply)(nil),       // 5: api.v1.StandardReply
	(*ClusterRoleReply)(nil),    // 6: api.v1.ClusterRoleReply
	(*GroupVersionKind)(nil),    // 7: api.v1.GroupVersionKind
	(*Rule)(nil),                // 8: api.v1.Rule
	(*ValidateRuleRequest)(nil), // 9: api.v1.ValidateRuleRequest
	(*ValidateRuleReply)(nil),   // 10: api.v1.ValidateRuleReply
	(*RegisterRuleRequest)(nil), // 11: api.v1.RegisterRuleRequest
	(*RegisterRuleReply)(nil),   // 12: api.v1.RegisterRuleReply
}
var file_pkg_authx_grpc_proto_api_proto_depIdxs = []int32{
	2,  // 0: api.v1.ClusterRoleRequest.appMeta:type_name -> api.v1.AppMeta
	3,  // 1: api.v1.ClusterRoleRequest.accountMeta:type_name -> api.v1.AccountMeta
	5,  // 2: api.v1.ClusterRoleReply.result:type_name -> api.v1.StandardReply
	7,  // 3: api.v1.Rule.groupVersionKind:type_name -> api.v1.GroupVersionKind
	2,  // 4: api.v1.ValidateRuleRequest.appMeta:type_name -> api.v1.AppMeta
	3,  // 5: api.v1.ValidateRuleRequest.accountMeta:type_name -> api.v1.AccountMeta
	8,  // 6: api.v1.ValidateRuleRequest.rule:type_name -> api.v1.Rule
	5,  // 7: api.v1.ValidateRuleReply.result:type_name -> api.v1.StandardReply
	2,  // 8: api.v1.RegisterRuleRequest.appMeta:type_name -> api.v1.AppMeta
	3,  // 9: api.v1.RegisterRuleRequest.accountMeta:type_name -> api.v1.AccountMeta
	5,  // 10: api.v1.RegisterRuleReply.result:type_name -> api.v1.StandardReply
	0,  // 11: api.v1.AuthxApi.KeepAlive:input_type -> api.v1.Ping
	11, // 12: api.v1.AuthxApi.RegisterRule:input_type -> api.v1.RegisterRuleRequest
	4,  // 13: api.v1.AuthxApi.ClusterRole:input_type -> api.v1.ClusterRoleRequest
	9,  // 14: api.v1.AuthxApi.ValidateRule:input_type -> api.v1.ValidateRuleRequest
	1,  // 15: api.v1.AuthxApi.KeepAlive:output_type -> api.v1.Pong
	12, // 16: api.v1.AuthxApi.RegisterRule:output_type -> api.v1.RegisterRuleReply
	6,  // 17: api.v1.AuthxApi.ClusterRole:output_type -> api.v1.ClusterRoleReply
	10, // 18: api.v1.AuthxApi.ValidateRule:output_type -> api.v1.ValidateRuleReply
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_authx_grpc_proto_api_proto_init() }
func file_pkg_authx_grpc_proto_api_proto_init() {
	if File_pkg_authx_grpc_proto_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_authx_grpc_proto_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandardReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterRoleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupVersionKind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateRuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateRuleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_authx_grpc_proto_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRuleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_authx_grpc_proto_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_authx_grpc_proto_api_proto_goTypes,
		DependencyIndexes: file_pkg_authx_grpc_proto_api_proto_depIdxs,
		MessageInfos:      file_pkg_authx_grpc_proto_api_proto_msgTypes,
	}.Build()
	File_pkg_authx_grpc_proto_api_proto = out.File
	file_pkg_authx_grpc_proto_api_proto_rawDesc = nil
	file_pkg_authx_grpc_proto_api_proto_goTypes = nil
	file_pkg_authx_grpc_proto_api_proto_depIdxs = nil
}
