//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	rbac "github.com/kzz45/neverdown/pkg/apis/rbac"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AccountMeta)(nil), (*rbac.AccountMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccountMeta_To_rbac_AccountMeta(a.(*AccountMeta), b.(*rbac.AccountMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.AccountMeta)(nil), (*AccountMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_AccountMeta_To_v1_AccountMeta(a.(*rbac.AccountMeta), b.(*AccountMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*App)(nil), (*rbac.App)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_App_To_rbac_App(a.(*App), b.(*rbac.App), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.App)(nil), (*App)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_App_To_v1_App(a.(*rbac.App), b.(*App), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppList)(nil), (*rbac.AppList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AppList_To_rbac_AppList(a.(*AppList), b.(*rbac.AppList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.AppList)(nil), (*AppList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_AppList_To_v1_AppList(a.(*rbac.AppList), b.(*AppList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppServiceAccount)(nil), (*rbac.AppServiceAccount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AppServiceAccount_To_rbac_AppServiceAccount(a.(*AppServiceAccount), b.(*rbac.AppServiceAccount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.AppServiceAccount)(nil), (*AppServiceAccount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_AppServiceAccount_To_v1_AppServiceAccount(a.(*rbac.AppServiceAccount), b.(*AppServiceAccount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppServiceAccountList)(nil), (*rbac.AppServiceAccountList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AppServiceAccountList_To_rbac_AppServiceAccountList(a.(*AppServiceAccountList), b.(*rbac.AppServiceAccountList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.AppServiceAccountList)(nil), (*AppServiceAccountList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_AppServiceAccountList_To_v1_AppServiceAccountList(a.(*rbac.AppServiceAccountList), b.(*AppServiceAccountList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppServiceAccountSpec)(nil), (*rbac.AppServiceAccountSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AppServiceAccountSpec_To_rbac_AppServiceAccountSpec(a.(*AppServiceAccountSpec), b.(*rbac.AppServiceAccountSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.AppServiceAccountSpec)(nil), (*AppServiceAccountSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_AppServiceAccountSpec_To_v1_AppServiceAccountSpec(a.(*rbac.AppServiceAccountSpec), b.(*AppServiceAccountSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppSpec)(nil), (*rbac.AppSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AppSpec_To_rbac_AppSpec(a.(*AppSpec), b.(*rbac.AppSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.AppSpec)(nil), (*AppSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_AppSpec_To_v1_AppSpec(a.(*rbac.AppSpec), b.(*AppSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterRole)(nil), (*rbac.ClusterRole)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterRole_To_rbac_ClusterRole(a.(*ClusterRole), b.(*rbac.ClusterRole), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.ClusterRole)(nil), (*ClusterRole)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_ClusterRole_To_v1_ClusterRole(a.(*rbac.ClusterRole), b.(*ClusterRole), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterRoleList)(nil), (*rbac.ClusterRoleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterRoleList_To_rbac_ClusterRoleList(a.(*ClusterRoleList), b.(*rbac.ClusterRoleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.ClusterRoleList)(nil), (*ClusterRoleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_ClusterRoleList_To_v1_ClusterRoleList(a.(*rbac.ClusterRoleList), b.(*ClusterRoleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterRoleSpec)(nil), (*rbac.ClusterRoleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterRoleSpec_To_rbac_ClusterRoleSpec(a.(*ClusterRoleSpec), b.(*rbac.ClusterRoleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.ClusterRoleSpec)(nil), (*ClusterRoleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_ClusterRoleSpec_To_v1_ClusterRoleSpec(a.(*rbac.ClusterRoleSpec), b.(*ClusterRoleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GroupVersionKind)(nil), (*rbac.GroupVersionKind)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GroupVersionKind_To_rbac_GroupVersionKind(a.(*GroupVersionKind), b.(*rbac.GroupVersionKind), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.GroupVersionKind)(nil), (*GroupVersionKind)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_GroupVersionKind_To_v1_GroupVersionKind(a.(*rbac.GroupVersionKind), b.(*GroupVersionKind), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GroupVersionKindRule)(nil), (*rbac.GroupVersionKindRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GroupVersionKindRule_To_rbac_GroupVersionKindRule(a.(*GroupVersionKindRule), b.(*rbac.GroupVersionKindRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.GroupVersionKindRule)(nil), (*GroupVersionKindRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_GroupVersionKindRule_To_v1_GroupVersionKindRule(a.(*rbac.GroupVersionKindRule), b.(*GroupVersionKindRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GroupVersionKindRuleList)(nil), (*rbac.GroupVersionKindRuleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_GroupVersionKindRuleList_To_rbac_GroupVersionKindRuleList(a.(*GroupVersionKindRuleList), b.(*rbac.GroupVersionKindRuleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.GroupVersionKindRuleList)(nil), (*GroupVersionKindRuleList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_GroupVersionKindRuleList_To_v1_GroupVersionKindRuleList(a.(*rbac.GroupVersionKindRuleList), b.(*GroupVersionKindRuleList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicyRule)(nil), (*rbac.PolicyRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PolicyRule_To_rbac_PolicyRule(a.(*PolicyRule), b.(*rbac.PolicyRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.PolicyRule)(nil), (*PolicyRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_PolicyRule_To_v1_PolicyRule(a.(*rbac.PolicyRule), b.(*PolicyRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RbacServiceAccount)(nil), (*rbac.RbacServiceAccount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RbacServiceAccount_To_rbac_RbacServiceAccount(a.(*RbacServiceAccount), b.(*rbac.RbacServiceAccount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.RbacServiceAccount)(nil), (*RbacServiceAccount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_RbacServiceAccount_To_v1_RbacServiceAccount(a.(*rbac.RbacServiceAccount), b.(*RbacServiceAccount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RbacServiceAccountList)(nil), (*rbac.RbacServiceAccountList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RbacServiceAccountList_To_rbac_RbacServiceAccountList(a.(*RbacServiceAccountList), b.(*rbac.RbacServiceAccountList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.RbacServiceAccountList)(nil), (*RbacServiceAccountList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_RbacServiceAccountList_To_v1_RbacServiceAccountList(a.(*rbac.RbacServiceAccountList), b.(*RbacServiceAccountList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RbacServiceAccountSpec)(nil), (*rbac.RbacServiceAccountSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RbacServiceAccountSpec_To_rbac_RbacServiceAccountSpec(a.(*RbacServiceAccountSpec), b.(*rbac.RbacServiceAccountSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.RbacServiceAccountSpec)(nil), (*RbacServiceAccountSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_RbacServiceAccountSpec_To_v1_RbacServiceAccountSpec(a.(*rbac.RbacServiceAccountSpec), b.(*RbacServiceAccountSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleRef)(nil), (*rbac.RoleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RoleRef_To_rbac_RoleRef(a.(*RoleRef), b.(*rbac.RoleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.RoleRef)(nil), (*RoleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_RoleRef_To_v1_RoleRef(a.(*rbac.RoleRef), b.(*RoleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RuleSpec)(nil), (*rbac.RuleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RuleSpec_To_rbac_RuleSpec(a.(*RuleSpec), b.(*rbac.RuleSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbac.RuleSpec)(nil), (*RuleSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbac_RuleSpec_To_v1_RuleSpec(a.(*rbac.RuleSpec), b.(*RuleSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_AccountMeta_To_rbac_AccountMeta(in *AccountMeta, out *rbac.AccountMeta, s conversion.Scope) error {
	out.Username = in.Username
	out.Nickname = in.Nickname
	out.Password = in.Password
	out.Email = in.Email
	return nil
}

// Convert_v1_AccountMeta_To_rbac_AccountMeta is an autogenerated conversion function.
func Convert_v1_AccountMeta_To_rbac_AccountMeta(in *AccountMeta, out *rbac.AccountMeta, s conversion.Scope) error {
	return autoConvert_v1_AccountMeta_To_rbac_AccountMeta(in, out, s)
}

func autoConvert_rbac_AccountMeta_To_v1_AccountMeta(in *rbac.AccountMeta, out *AccountMeta, s conversion.Scope) error {
	out.Username = in.Username
	out.Nickname = in.Nickname
	out.Password = in.Password
	out.Email = in.Email
	return nil
}

// Convert_rbac_AccountMeta_To_v1_AccountMeta is an autogenerated conversion function.
func Convert_rbac_AccountMeta_To_v1_AccountMeta(in *rbac.AccountMeta, out *AccountMeta, s conversion.Scope) error {
	return autoConvert_rbac_AccountMeta_To_v1_AccountMeta(in, out, s)
}

func autoConvert_v1_App_To_rbac_App(in *App, out *rbac.App, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_AppSpec_To_rbac_AppSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_App_To_rbac_App is an autogenerated conversion function.
func Convert_v1_App_To_rbac_App(in *App, out *rbac.App, s conversion.Scope) error {
	return autoConvert_v1_App_To_rbac_App(in, out, s)
}

func autoConvert_rbac_App_To_v1_App(in *rbac.App, out *App, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_rbac_AppSpec_To_v1_AppSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_rbac_App_To_v1_App is an autogenerated conversion function.
func Convert_rbac_App_To_v1_App(in *rbac.App, out *App, s conversion.Scope) error {
	return autoConvert_rbac_App_To_v1_App(in, out, s)
}

func autoConvert_v1_AppList_To_rbac_AppList(in *AppList, out *rbac.AppList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]rbac.App)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_AppList_To_rbac_AppList is an autogenerated conversion function.
func Convert_v1_AppList_To_rbac_AppList(in *AppList, out *rbac.AppList, s conversion.Scope) error {
	return autoConvert_v1_AppList_To_rbac_AppList(in, out, s)
}

func autoConvert_rbac_AppList_To_v1_AppList(in *rbac.AppList, out *AppList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]App)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_rbac_AppList_To_v1_AppList is an autogenerated conversion function.
func Convert_rbac_AppList_To_v1_AppList(in *rbac.AppList, out *AppList, s conversion.Scope) error {
	return autoConvert_rbac_AppList_To_v1_AppList(in, out, s)
}

func autoConvert_v1_AppServiceAccount_To_rbac_AppServiceAccount(in *AppServiceAccount, out *rbac.AppServiceAccount, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_AppServiceAccountSpec_To_rbac_AppServiceAccountSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_AppServiceAccount_To_rbac_AppServiceAccount is an autogenerated conversion function.
func Convert_v1_AppServiceAccount_To_rbac_AppServiceAccount(in *AppServiceAccount, out *rbac.AppServiceAccount, s conversion.Scope) error {
	return autoConvert_v1_AppServiceAccount_To_rbac_AppServiceAccount(in, out, s)
}

func autoConvert_rbac_AppServiceAccount_To_v1_AppServiceAccount(in *rbac.AppServiceAccount, out *AppServiceAccount, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_rbac_AppServiceAccountSpec_To_v1_AppServiceAccountSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_rbac_AppServiceAccount_To_v1_AppServiceAccount is an autogenerated conversion function.
func Convert_rbac_AppServiceAccount_To_v1_AppServiceAccount(in *rbac.AppServiceAccount, out *AppServiceAccount, s conversion.Scope) error {
	return autoConvert_rbac_AppServiceAccount_To_v1_AppServiceAccount(in, out, s)
}

func autoConvert_v1_AppServiceAccountList_To_rbac_AppServiceAccountList(in *AppServiceAccountList, out *rbac.AppServiceAccountList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]rbac.AppServiceAccount)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_AppServiceAccountList_To_rbac_AppServiceAccountList is an autogenerated conversion function.
func Convert_v1_AppServiceAccountList_To_rbac_AppServiceAccountList(in *AppServiceAccountList, out *rbac.AppServiceAccountList, s conversion.Scope) error {
	return autoConvert_v1_AppServiceAccountList_To_rbac_AppServiceAccountList(in, out, s)
}

func autoConvert_rbac_AppServiceAccountList_To_v1_AppServiceAccountList(in *rbac.AppServiceAccountList, out *AppServiceAccountList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AppServiceAccount)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_rbac_AppServiceAccountList_To_v1_AppServiceAccountList is an autogenerated conversion function.
func Convert_rbac_AppServiceAccountList_To_v1_AppServiceAccountList(in *rbac.AppServiceAccountList, out *AppServiceAccountList, s conversion.Scope) error {
	return autoConvert_rbac_AppServiceAccountList_To_v1_AppServiceAccountList(in, out, s)
}

func autoConvert_v1_AppServiceAccountSpec_To_rbac_AppServiceAccountSpec(in *AppServiceAccountSpec, out *rbac.AppServiceAccountSpec, s conversion.Scope) error {
	out.Desc = in.Desc
	if err := Convert_v1_RoleRef_To_rbac_RoleRef(&in.RoleRef, &out.RoleRef, s); err != nil {
		return err
	}
	if err := Convert_v1_AccountMeta_To_rbac_AccountMeta(&in.AccountMeta, &out.AccountMeta, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_AppServiceAccountSpec_To_rbac_AppServiceAccountSpec is an autogenerated conversion function.
func Convert_v1_AppServiceAccountSpec_To_rbac_AppServiceAccountSpec(in *AppServiceAccountSpec, out *rbac.AppServiceAccountSpec, s conversion.Scope) error {
	return autoConvert_v1_AppServiceAccountSpec_To_rbac_AppServiceAccountSpec(in, out, s)
}

func autoConvert_rbac_AppServiceAccountSpec_To_v1_AppServiceAccountSpec(in *rbac.AppServiceAccountSpec, out *AppServiceAccountSpec, s conversion.Scope) error {
	out.Desc = in.Desc
	if err := Convert_rbac_RoleRef_To_v1_RoleRef(&in.RoleRef, &out.RoleRef, s); err != nil {
		return err
	}
	if err := Convert_rbac_AccountMeta_To_v1_AccountMeta(&in.AccountMeta, &out.AccountMeta, s); err != nil {
		return err
	}
	return nil
}

// Convert_rbac_AppServiceAccountSpec_To_v1_AppServiceAccountSpec is an autogenerated conversion function.
func Convert_rbac_AppServiceAccountSpec_To_v1_AppServiceAccountSpec(in *rbac.AppServiceAccountSpec, out *AppServiceAccountSpec, s conversion.Scope) error {
	return autoConvert_rbac_AppServiceAccountSpec_To_v1_AppServiceAccountSpec(in, out, s)
}

func autoConvert_v1_AppSpec_To_rbac_AppSpec(in *AppSpec, out *rbac.AppSpec, s conversion.Scope) error {
	out.Id = in.Id
	out.Secret = in.Secret
	out.Desc = in.Desc
	return nil
}

// Convert_v1_AppSpec_To_rbac_AppSpec is an autogenerated conversion function.
func Convert_v1_AppSpec_To_rbac_AppSpec(in *AppSpec, out *rbac.AppSpec, s conversion.Scope) error {
	return autoConvert_v1_AppSpec_To_rbac_AppSpec(in, out, s)
}

func autoConvert_rbac_AppSpec_To_v1_AppSpec(in *rbac.AppSpec, out *AppSpec, s conversion.Scope) error {
	out.Id = in.Id
	out.Secret = in.Secret
	out.Desc = in.Desc
	return nil
}

// Convert_rbac_AppSpec_To_v1_AppSpec is an autogenerated conversion function.
func Convert_rbac_AppSpec_To_v1_AppSpec(in *rbac.AppSpec, out *AppSpec, s conversion.Scope) error {
	return autoConvert_rbac_AppSpec_To_v1_AppSpec(in, out, s)
}

func autoConvert_v1_ClusterRole_To_rbac_ClusterRole(in *ClusterRole, out *rbac.ClusterRole, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ClusterRoleSpec_To_rbac_ClusterRoleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ClusterRole_To_rbac_ClusterRole is an autogenerated conversion function.
func Convert_v1_ClusterRole_To_rbac_ClusterRole(in *ClusterRole, out *rbac.ClusterRole, s conversion.Scope) error {
	return autoConvert_v1_ClusterRole_To_rbac_ClusterRole(in, out, s)
}

func autoConvert_rbac_ClusterRole_To_v1_ClusterRole(in *rbac.ClusterRole, out *ClusterRole, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_rbac_ClusterRoleSpec_To_v1_ClusterRoleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_rbac_ClusterRole_To_v1_ClusterRole is an autogenerated conversion function.
func Convert_rbac_ClusterRole_To_v1_ClusterRole(in *rbac.ClusterRole, out *ClusterRole, s conversion.Scope) error {
	return autoConvert_rbac_ClusterRole_To_v1_ClusterRole(in, out, s)
}

func autoConvert_v1_ClusterRoleList_To_rbac_ClusterRoleList(in *ClusterRoleList, out *rbac.ClusterRoleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]rbac.ClusterRole)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ClusterRoleList_To_rbac_ClusterRoleList is an autogenerated conversion function.
func Convert_v1_ClusterRoleList_To_rbac_ClusterRoleList(in *ClusterRoleList, out *rbac.ClusterRoleList, s conversion.Scope) error {
	return autoConvert_v1_ClusterRoleList_To_rbac_ClusterRoleList(in, out, s)
}

func autoConvert_rbac_ClusterRoleList_To_v1_ClusterRoleList(in *rbac.ClusterRoleList, out *ClusterRoleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterRole)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_rbac_ClusterRoleList_To_v1_ClusterRoleList is an autogenerated conversion function.
func Convert_rbac_ClusterRoleList_To_v1_ClusterRoleList(in *rbac.ClusterRoleList, out *ClusterRoleList, s conversion.Scope) error {
	return autoConvert_rbac_ClusterRoleList_To_v1_ClusterRoleList(in, out, s)
}

func autoConvert_v1_ClusterRoleSpec_To_rbac_ClusterRoleSpec(in *ClusterRoleSpec, out *rbac.ClusterRoleSpec, s conversion.Scope) error {
	out.Desc = in.Desc
	out.Rules = *(*[]rbac.PolicyRule)(unsafe.Pointer(&in.Rules))
	return nil
}

// Convert_v1_ClusterRoleSpec_To_rbac_ClusterRoleSpec is an autogenerated conversion function.
func Convert_v1_ClusterRoleSpec_To_rbac_ClusterRoleSpec(in *ClusterRoleSpec, out *rbac.ClusterRoleSpec, s conversion.Scope) error {
	return autoConvert_v1_ClusterRoleSpec_To_rbac_ClusterRoleSpec(in, out, s)
}

func autoConvert_rbac_ClusterRoleSpec_To_v1_ClusterRoleSpec(in *rbac.ClusterRoleSpec, out *ClusterRoleSpec, s conversion.Scope) error {
	out.Desc = in.Desc
	out.Rules = *(*[]PolicyRule)(unsafe.Pointer(&in.Rules))
	return nil
}

// Convert_rbac_ClusterRoleSpec_To_v1_ClusterRoleSpec is an autogenerated conversion function.
func Convert_rbac_ClusterRoleSpec_To_v1_ClusterRoleSpec(in *rbac.ClusterRoleSpec, out *ClusterRoleSpec, s conversion.Scope) error {
	return autoConvert_rbac_ClusterRoleSpec_To_v1_ClusterRoleSpec(in, out, s)
}

func autoConvert_v1_GroupVersionKind_To_rbac_GroupVersionKind(in *GroupVersionKind, out *rbac.GroupVersionKind, s conversion.Scope) error {
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	return nil
}

// Convert_v1_GroupVersionKind_To_rbac_GroupVersionKind is an autogenerated conversion function.
func Convert_v1_GroupVersionKind_To_rbac_GroupVersionKind(in *GroupVersionKind, out *rbac.GroupVersionKind, s conversion.Scope) error {
	return autoConvert_v1_GroupVersionKind_To_rbac_GroupVersionKind(in, out, s)
}

func autoConvert_rbac_GroupVersionKind_To_v1_GroupVersionKind(in *rbac.GroupVersionKind, out *GroupVersionKind, s conversion.Scope) error {
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	return nil
}

// Convert_rbac_GroupVersionKind_To_v1_GroupVersionKind is an autogenerated conversion function.
func Convert_rbac_GroupVersionKind_To_v1_GroupVersionKind(in *rbac.GroupVersionKind, out *GroupVersionKind, s conversion.Scope) error {
	return autoConvert_rbac_GroupVersionKind_To_v1_GroupVersionKind(in, out, s)
}

func autoConvert_v1_GroupVersionKindRule_To_rbac_GroupVersionKindRule(in *GroupVersionKindRule, out *rbac.GroupVersionKindRule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_RuleSpec_To_rbac_RuleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_GroupVersionKindRule_To_rbac_GroupVersionKindRule is an autogenerated conversion function.
func Convert_v1_GroupVersionKindRule_To_rbac_GroupVersionKindRule(in *GroupVersionKindRule, out *rbac.GroupVersionKindRule, s conversion.Scope) error {
	return autoConvert_v1_GroupVersionKindRule_To_rbac_GroupVersionKindRule(in, out, s)
}

func autoConvert_rbac_GroupVersionKindRule_To_v1_GroupVersionKindRule(in *rbac.GroupVersionKindRule, out *GroupVersionKindRule, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_rbac_RuleSpec_To_v1_RuleSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_rbac_GroupVersionKindRule_To_v1_GroupVersionKindRule is an autogenerated conversion function.
func Convert_rbac_GroupVersionKindRule_To_v1_GroupVersionKindRule(in *rbac.GroupVersionKindRule, out *GroupVersionKindRule, s conversion.Scope) error {
	return autoConvert_rbac_GroupVersionKindRule_To_v1_GroupVersionKindRule(in, out, s)
}

func autoConvert_v1_GroupVersionKindRuleList_To_rbac_GroupVersionKindRuleList(in *GroupVersionKindRuleList, out *rbac.GroupVersionKindRuleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]rbac.GroupVersionKindRule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_GroupVersionKindRuleList_To_rbac_GroupVersionKindRuleList is an autogenerated conversion function.
func Convert_v1_GroupVersionKindRuleList_To_rbac_GroupVersionKindRuleList(in *GroupVersionKindRuleList, out *rbac.GroupVersionKindRuleList, s conversion.Scope) error {
	return autoConvert_v1_GroupVersionKindRuleList_To_rbac_GroupVersionKindRuleList(in, out, s)
}

func autoConvert_rbac_GroupVersionKindRuleList_To_v1_GroupVersionKindRuleList(in *rbac.GroupVersionKindRuleList, out *GroupVersionKindRuleList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]GroupVersionKindRule)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_rbac_GroupVersionKindRuleList_To_v1_GroupVersionKindRuleList is an autogenerated conversion function.
func Convert_rbac_GroupVersionKindRuleList_To_v1_GroupVersionKindRuleList(in *rbac.GroupVersionKindRuleList, out *GroupVersionKindRuleList, s conversion.Scope) error {
	return autoConvert_rbac_GroupVersionKindRuleList_To_v1_GroupVersionKindRuleList(in, out, s)
}

func autoConvert_v1_PolicyRule_To_rbac_PolicyRule(in *PolicyRule, out *rbac.PolicyRule, s conversion.Scope) error {
	out.Namespace = in.Namespace
	if err := Convert_v1_GroupVersionKind_To_rbac_GroupVersionKind(&in.GroupVersionKind, &out.GroupVersionKind, s); err != nil {
		return err
	}
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_v1_PolicyRule_To_rbac_PolicyRule is an autogenerated conversion function.
func Convert_v1_PolicyRule_To_rbac_PolicyRule(in *PolicyRule, out *rbac.PolicyRule, s conversion.Scope) error {
	return autoConvert_v1_PolicyRule_To_rbac_PolicyRule(in, out, s)
}

func autoConvert_rbac_PolicyRule_To_v1_PolicyRule(in *rbac.PolicyRule, out *PolicyRule, s conversion.Scope) error {
	out.Namespace = in.Namespace
	if err := Convert_rbac_GroupVersionKind_To_v1_GroupVersionKind(&in.GroupVersionKind, &out.GroupVersionKind, s); err != nil {
		return err
	}
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_rbac_PolicyRule_To_v1_PolicyRule is an autogenerated conversion function.
func Convert_rbac_PolicyRule_To_v1_PolicyRule(in *rbac.PolicyRule, out *PolicyRule, s conversion.Scope) error {
	return autoConvert_rbac_PolicyRule_To_v1_PolicyRule(in, out, s)
}

func autoConvert_v1_RbacServiceAccount_To_rbac_RbacServiceAccount(in *RbacServiceAccount, out *rbac.RbacServiceAccount, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_RbacServiceAccountSpec_To_rbac_RbacServiceAccountSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_RbacServiceAccount_To_rbac_RbacServiceAccount is an autogenerated conversion function.
func Convert_v1_RbacServiceAccount_To_rbac_RbacServiceAccount(in *RbacServiceAccount, out *rbac.RbacServiceAccount, s conversion.Scope) error {
	return autoConvert_v1_RbacServiceAccount_To_rbac_RbacServiceAccount(in, out, s)
}

func autoConvert_rbac_RbacServiceAccount_To_v1_RbacServiceAccount(in *rbac.RbacServiceAccount, out *RbacServiceAccount, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_rbac_RbacServiceAccountSpec_To_v1_RbacServiceAccountSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_rbac_RbacServiceAccount_To_v1_RbacServiceAccount is an autogenerated conversion function.
func Convert_rbac_RbacServiceAccount_To_v1_RbacServiceAccount(in *rbac.RbacServiceAccount, out *RbacServiceAccount, s conversion.Scope) error {
	return autoConvert_rbac_RbacServiceAccount_To_v1_RbacServiceAccount(in, out, s)
}

func autoConvert_v1_RbacServiceAccountList_To_rbac_RbacServiceAccountList(in *RbacServiceAccountList, out *rbac.RbacServiceAccountList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]rbac.RbacServiceAccount)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_RbacServiceAccountList_To_rbac_RbacServiceAccountList is an autogenerated conversion function.
func Convert_v1_RbacServiceAccountList_To_rbac_RbacServiceAccountList(in *RbacServiceAccountList, out *rbac.RbacServiceAccountList, s conversion.Scope) error {
	return autoConvert_v1_RbacServiceAccountList_To_rbac_RbacServiceAccountList(in, out, s)
}

func autoConvert_rbac_RbacServiceAccountList_To_v1_RbacServiceAccountList(in *rbac.RbacServiceAccountList, out *RbacServiceAccountList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RbacServiceAccount)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_rbac_RbacServiceAccountList_To_v1_RbacServiceAccountList is an autogenerated conversion function.
func Convert_rbac_RbacServiceAccountList_To_v1_RbacServiceAccountList(in *rbac.RbacServiceAccountList, out *RbacServiceAccountList, s conversion.Scope) error {
	return autoConvert_rbac_RbacServiceAccountList_To_v1_RbacServiceAccountList(in, out, s)
}

func autoConvert_v1_RbacServiceAccountSpec_To_rbac_RbacServiceAccountSpec(in *RbacServiceAccountSpec, out *rbac.RbacServiceAccountSpec, s conversion.Scope) error {
	if err := Convert_v1_AccountMeta_To_rbac_AccountMeta(&in.AccountMeta, &out.AccountMeta, s); err != nil {
		return err
	}
	out.Apps = *(*[]string)(unsafe.Pointer(&in.Apps))
	return nil
}

// Convert_v1_RbacServiceAccountSpec_To_rbac_RbacServiceAccountSpec is an autogenerated conversion function.
func Convert_v1_RbacServiceAccountSpec_To_rbac_RbacServiceAccountSpec(in *RbacServiceAccountSpec, out *rbac.RbacServiceAccountSpec, s conversion.Scope) error {
	return autoConvert_v1_RbacServiceAccountSpec_To_rbac_RbacServiceAccountSpec(in, out, s)
}

func autoConvert_rbac_RbacServiceAccountSpec_To_v1_RbacServiceAccountSpec(in *rbac.RbacServiceAccountSpec, out *RbacServiceAccountSpec, s conversion.Scope) error {
	if err := Convert_rbac_AccountMeta_To_v1_AccountMeta(&in.AccountMeta, &out.AccountMeta, s); err != nil {
		return err
	}
	out.Apps = *(*[]string)(unsafe.Pointer(&in.Apps))
	return nil
}

// Convert_rbac_RbacServiceAccountSpec_To_v1_RbacServiceAccountSpec is an autogenerated conversion function.
func Convert_rbac_RbacServiceAccountSpec_To_v1_RbacServiceAccountSpec(in *rbac.RbacServiceAccountSpec, out *RbacServiceAccountSpec, s conversion.Scope) error {
	return autoConvert_rbac_RbacServiceAccountSpec_To_v1_RbacServiceAccountSpec(in, out, s)
}

func autoConvert_v1_RoleRef_To_rbac_RoleRef(in *RoleRef, out *rbac.RoleRef, s conversion.Scope) error {
	out.ClusterRoleName = in.ClusterRoleName
	return nil
}

// Convert_v1_RoleRef_To_rbac_RoleRef is an autogenerated conversion function.
func Convert_v1_RoleRef_To_rbac_RoleRef(in *RoleRef, out *rbac.RoleRef, s conversion.Scope) error {
	return autoConvert_v1_RoleRef_To_rbac_RoleRef(in, out, s)
}

func autoConvert_rbac_RoleRef_To_v1_RoleRef(in *rbac.RoleRef, out *RoleRef, s conversion.Scope) error {
	out.ClusterRoleName = in.ClusterRoleName
	return nil
}

// Convert_rbac_RoleRef_To_v1_RoleRef is an autogenerated conversion function.
func Convert_rbac_RoleRef_To_v1_RoleRef(in *rbac.RoleRef, out *RoleRef, s conversion.Scope) error {
	return autoConvert_rbac_RoleRef_To_v1_RoleRef(in, out, s)
}

func autoConvert_v1_RuleSpec_To_rbac_RuleSpec(in *RuleSpec, out *rbac.RuleSpec, s conversion.Scope) error {
	if err := Convert_v1_GroupVersionKind_To_rbac_GroupVersionKind(&in.GroupVersionKind, &out.GroupVersionKind, s); err != nil {
		return err
	}
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_v1_RuleSpec_To_rbac_RuleSpec is an autogenerated conversion function.
func Convert_v1_RuleSpec_To_rbac_RuleSpec(in *RuleSpec, out *rbac.RuleSpec, s conversion.Scope) error {
	return autoConvert_v1_RuleSpec_To_rbac_RuleSpec(in, out, s)
}

func autoConvert_rbac_RuleSpec_To_v1_RuleSpec(in *rbac.RuleSpec, out *RuleSpec, s conversion.Scope) error {
	if err := Convert_rbac_GroupVersionKind_To_v1_GroupVersionKind(&in.GroupVersionKind, &out.GroupVersionKind, s); err != nil {
		return err
	}
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_rbac_RuleSpec_To_v1_RuleSpec is an autogenerated conversion function.
func Convert_rbac_RuleSpec_To_v1_RuleSpec(in *rbac.RuleSpec, out *RuleSpec, s conversion.Scope) error {
	return autoConvert_rbac_RuleSpec_To_v1_RuleSpec(in, out, s)
}
