/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/kzz45/neverdown/pkg/apis/audit/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRecorders implements RecorderInterface
type FakeRecorders struct {
	Fake *FakeAuditV1
	ns   string
}

var recordersResource = v1.SchemeGroupVersion.WithResource("recorders")

var recordersKind = v1.SchemeGroupVersion.WithKind("Recorder")

// Get takes name of the recorder, and returns the corresponding recorder object, and an error if there is any.
func (c *FakeRecorders) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Recorder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(recordersResource, c.ns, name), &v1.Recorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Recorder), err
}

// List takes label and field selectors, and returns the list of Recorders that match those selectors.
func (c *FakeRecorders) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RecorderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(recordersResource, recordersKind, c.ns, opts), &v1.RecorderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.RecorderList{ListMeta: obj.(*v1.RecorderList).ListMeta}
	for _, item := range obj.(*v1.RecorderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested recorders.
func (c *FakeRecorders) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(recordersResource, c.ns, opts))

}

// Create takes the representation of a recorder and creates it.  Returns the server's representation of the recorder, and an error, if there is any.
func (c *FakeRecorders) Create(ctx context.Context, recorder *v1.Recorder, opts metav1.CreateOptions) (result *v1.Recorder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(recordersResource, c.ns, recorder), &v1.Recorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Recorder), err
}

// Update takes the representation of a recorder and updates it. Returns the server's representation of the recorder, and an error, if there is any.
func (c *FakeRecorders) Update(ctx context.Context, recorder *v1.Recorder, opts metav1.UpdateOptions) (result *v1.Recorder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(recordersResource, c.ns, recorder), &v1.Recorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Recorder), err
}

// Delete takes name of the recorder and deletes it. Returns an error if one occurs.
func (c *FakeRecorders) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(recordersResource, c.ns, name, opts), &v1.Recorder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRecorders) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(recordersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.RecorderList{})
	return err
}

// Patch applies the patch and returns the patched recorder.
func (c *FakeRecorders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Recorder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(recordersResource, c.ns, name, pt, data, subresources...), &v1.Recorder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Recorder), err
}
