apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: etcds.openx.neverdown.io
spec:
  group: openx.neverdown.io
  scope: Namespaced
  names:
    plural: etcds
    singular: etcd
    kind: Etcd
    shortNames:
    - etcd
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
      priority: 0
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              observedGeneration:
                format: int64
                type: integer
              replicas:
                format: int32
                type: integer
              readyReplicas:
                format: int32
                type: integer
              currentReplicas:
                format: int32
                type: integer
              updatedReplicas:
                format: int32
                type: integer
              currentRevision:
                type: string
              updateRevision:
                type: string
              collisionCount:
                format: int32
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

