apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openxes.openx.neverdown.io
spec:
  group: openx.neverdown.io
  scope: Namespaced
  names:
    plural: openxes
    singular: openx
    kind: Openx
    shortNames:
    - openx
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
      priority: 0
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              applications:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  x-kubernetes-validations:
                  - rule: "self.watchPolicy == 'in-place-upgrade' && has(self.horizontalPodAutoscalerSpec) && self.horizontalPodAutoscalerSpec.minReplicas >= 0"
                    message: "hpa should not be chose when the watchPolicy was in-place-upgrade"
                  required: ["watchPolicy"]
                  properties:
                    watchPolicy:
                      type: string
                    minReplicas:
                      type: integer
                    maxReplicas:
                      type: integer
                    horizontalPodAutoscalerSpec:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      x-kubernetes-validations:
                      - rule: "self.maxReplicas < self.minReplicas"
                        message: "maxReplicas should be greater than or equal to minReplicas"
                      properties:
                        minReplicas:
                          type: integer
                        maxReplicas:
                          type: integer
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true

