//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	openx "github.com/kzz45/neverdown/pkg/apis/openx"
	v2 "k8s.io/api/autoscaling/v2"
	corev1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AccessControl)(nil), (*openx.AccessControl)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccessControl_To_openx_AccessControl(a.(*AccessControl), b.(*openx.AccessControl), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.AccessControl)(nil), (*AccessControl)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_AccessControl_To_v1_AccessControl(a.(*openx.AccessControl), b.(*AccessControl), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AccessControlList)(nil), (*openx.AccessControlList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccessControlList_To_openx_AccessControlList(a.(*AccessControlList), b.(*openx.AccessControlList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.AccessControlList)(nil), (*AccessControlList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_AccessControlList_To_v1_AccessControlList(a.(*openx.AccessControlList), b.(*AccessControlList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AccessControlSpec)(nil), (*openx.AccessControlSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AccessControlSpec_To_openx_AccessControlSpec(a.(*AccessControlSpec), b.(*openx.AccessControlSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.AccessControlSpec)(nil), (*AccessControlSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_AccessControlSpec_To_v1_AccessControlSpec(a.(*openx.AccessControlSpec), b.(*AccessControlSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Affinity)(nil), (*openx.Affinity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Affinity_To_openx_Affinity(a.(*Affinity), b.(*openx.Affinity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.Affinity)(nil), (*Affinity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_Affinity_To_v1_Affinity(a.(*openx.Affinity), b.(*Affinity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AffinityList)(nil), (*openx.AffinityList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AffinityList_To_openx_AffinityList(a.(*AffinityList), b.(*openx.AffinityList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.AffinityList)(nil), (*AffinityList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_AffinityList_To_v1_AffinityList(a.(*openx.AffinityList), b.(*AffinityList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AffinitySpec)(nil), (*openx.AffinitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AffinitySpec_To_openx_AffinitySpec(a.(*AffinitySpec), b.(*openx.AffinitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.AffinitySpec)(nil), (*AffinitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_AffinitySpec_To_v1_AffinitySpec(a.(*openx.AffinitySpec), b.(*AffinitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*App)(nil), (*openx.App)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_App_To_openx_App(a.(*App), b.(*openx.App), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.App)(nil), (*App)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_App_To_v1_App(a.(*openx.App), b.(*App), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppStatus)(nil), (*openx.AppStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_AppStatus_To_openx_AppStatus(a.(*AppStatus), b.(*openx.AppStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.AppStatus)(nil), (*AppStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_AppStatus_To_v1_AppStatus(a.(*openx.AppStatus), b.(*AppStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudLoadBalancerObject)(nil), (*openx.CloudLoadBalancerObject)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(a.(*CloudLoadBalancerObject), b.(*openx.CloudLoadBalancerObject), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.CloudLoadBalancerObject)(nil), (*CloudLoadBalancerObject)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(a.(*openx.CloudLoadBalancerObject), b.(*CloudLoadBalancerObject), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudNetworkConfig)(nil), (*openx.CloudNetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CloudNetworkConfig_To_openx_CloudNetworkConfig(a.(*CloudNetworkConfig), b.(*openx.CloudNetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.CloudNetworkConfig)(nil), (*CloudNetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_CloudNetworkConfig_To_v1_CloudNetworkConfig(a.(*openx.CloudNetworkConfig), b.(*CloudNetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudSLB)(nil), (*openx.CloudSLB)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CloudSLB_To_openx_CloudSLB(a.(*CloudSLB), b.(*openx.CloudSLB), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.CloudSLB)(nil), (*CloudSLB)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_CloudSLB_To_v1_CloudSLB(a.(*openx.CloudSLB), b.(*CloudSLB), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterStatus)(nil), (*openx.ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterStatus_To_openx_ClusterStatus(a.(*ClusterStatus), b.(*openx.ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.ClusterStatus)(nil), (*ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_ClusterStatus_To_v1_ClusterStatus(a.(*openx.ClusterStatus), b.(*ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Etcd)(nil), (*openx.Etcd)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Etcd_To_openx_Etcd(a.(*Etcd), b.(*openx.Etcd), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.Etcd)(nil), (*Etcd)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_Etcd_To_v1_Etcd(a.(*openx.Etcd), b.(*Etcd), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdList)(nil), (*openx.EtcdList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_EtcdList_To_openx_EtcdList(a.(*EtcdList), b.(*openx.EtcdList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.EtcdList)(nil), (*EtcdList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_EtcdList_To_v1_EtcdList(a.(*openx.EtcdList), b.(*EtcdList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdSpec)(nil), (*openx.EtcdSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_EtcdSpec_To_openx_EtcdSpec(a.(*EtcdSpec), b.(*openx.EtcdSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.EtcdSpec)(nil), (*EtcdSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_EtcdSpec_To_v1_EtcdSpec(a.(*openx.EtcdSpec), b.(*EtcdSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LoadBalancer)(nil), (*openx.LoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LoadBalancer_To_openx_LoadBalancer(a.(*LoadBalancer), b.(*openx.LoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.LoadBalancer)(nil), (*LoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_LoadBalancer_To_v1_LoadBalancer(a.(*openx.LoadBalancer), b.(*LoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LoadBalancerList)(nil), (*openx.LoadBalancerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LoadBalancerList_To_openx_LoadBalancerList(a.(*LoadBalancerList), b.(*openx.LoadBalancerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.LoadBalancerList)(nil), (*LoadBalancerList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_LoadBalancerList_To_v1_LoadBalancerList(a.(*openx.LoadBalancerList), b.(*LoadBalancerList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LoadBalancerSpec)(nil), (*openx.LoadBalancerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LoadBalancerSpec_To_openx_LoadBalancerSpec(a.(*LoadBalancerSpec), b.(*openx.LoadBalancerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.LoadBalancerSpec)(nil), (*LoadBalancerSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_LoadBalancerSpec_To_v1_LoadBalancerSpec(a.(*openx.LoadBalancerSpec), b.(*LoadBalancerSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Mysql)(nil), (*openx.Mysql)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Mysql_To_openx_Mysql(a.(*Mysql), b.(*openx.Mysql), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.Mysql)(nil), (*Mysql)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_Mysql_To_v1_Mysql(a.(*openx.Mysql), b.(*Mysql), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MysqlConfig)(nil), (*openx.MysqlConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MysqlConfig_To_openx_MysqlConfig(a.(*MysqlConfig), b.(*openx.MysqlConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.MysqlConfig)(nil), (*MysqlConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_MysqlConfig_To_v1_MysqlConfig(a.(*openx.MysqlConfig), b.(*MysqlConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MysqlList)(nil), (*openx.MysqlList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MysqlList_To_openx_MysqlList(a.(*MysqlList), b.(*openx.MysqlList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.MysqlList)(nil), (*MysqlList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_MysqlList_To_v1_MysqlList(a.(*openx.MysqlList), b.(*MysqlList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MysqlServerConfig)(nil), (*openx.MysqlServerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MysqlServerConfig_To_openx_MysqlServerConfig(a.(*MysqlServerConfig), b.(*openx.MysqlServerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.MysqlServerConfig)(nil), (*MysqlServerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_MysqlServerConfig_To_v1_MysqlServerConfig(a.(*openx.MysqlServerConfig), b.(*MysqlServerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MysqlSpec)(nil), (*openx.MysqlSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_MysqlSpec_To_openx_MysqlSpec(a.(*MysqlSpec), b.(*openx.MysqlSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.MysqlSpec)(nil), (*MysqlSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_MysqlSpec_To_v1_MysqlSpec(a.(*openx.MysqlSpec), b.(*MysqlSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeSelector)(nil), (*openx.NodeSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NodeSelector_To_openx_NodeSelector(a.(*NodeSelector), b.(*openx.NodeSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.NodeSelector)(nil), (*NodeSelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_NodeSelector_To_v1_NodeSelector(a.(*openx.NodeSelector), b.(*NodeSelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeSelectorList)(nil), (*openx.NodeSelectorList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NodeSelectorList_To_openx_NodeSelectorList(a.(*NodeSelectorList), b.(*openx.NodeSelectorList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.NodeSelectorList)(nil), (*NodeSelectorList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_NodeSelectorList_To_v1_NodeSelectorList(a.(*openx.NodeSelectorList), b.(*NodeSelectorList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeSelectorSpec)(nil), (*openx.NodeSelectorSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NodeSelectorSpec_To_openx_NodeSelectorSpec(a.(*NodeSelectorSpec), b.(*openx.NodeSelectorSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.NodeSelectorSpec)(nil), (*NodeSelectorSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_NodeSelectorSpec_To_v1_NodeSelectorSpec(a.(*openx.NodeSelectorSpec), b.(*NodeSelectorSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Openx)(nil), (*openx.Openx)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Openx_To_openx_Openx(a.(*Openx), b.(*openx.Openx), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.Openx)(nil), (*Openx)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_Openx_To_v1_Openx(a.(*openx.Openx), b.(*Openx), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenxList)(nil), (*openx.OpenxList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OpenxList_To_openx_OpenxList(a.(*OpenxList), b.(*openx.OpenxList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.OpenxList)(nil), (*OpenxList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_OpenxList_To_v1_OpenxList(a.(*openx.OpenxList), b.(*OpenxList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenxSpec)(nil), (*openx.OpenxSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OpenxSpec_To_openx_OpenxSpec(a.(*OpenxSpec), b.(*openx.OpenxSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.OpenxSpec)(nil), (*OpenxSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_OpenxSpec_To_v1_OpenxSpec(a.(*openx.OpenxSpec), b.(*OpenxSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenxStatus)(nil), (*openx.OpenxStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OpenxStatus_To_openx_OpenxStatus(a.(*OpenxStatus), b.(*openx.OpenxStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.OpenxStatus)(nil), (*OpenxStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_OpenxStatus_To_v1_OpenxStatus(a.(*openx.OpenxStatus), b.(*OpenxStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersistentStorage)(nil), (*openx.PersistentStorage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PersistentStorage_To_openx_PersistentStorage(a.(*PersistentStorage), b.(*openx.PersistentStorage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.PersistentStorage)(nil), (*PersistentStorage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_PersistentStorage_To_v1_PersistentStorage(a.(*openx.PersistentStorage), b.(*PersistentStorage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Redis)(nil), (*openx.Redis)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Redis_To_openx_Redis(a.(*Redis), b.(*openx.Redis), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.Redis)(nil), (*Redis)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_Redis_To_v1_Redis(a.(*openx.Redis), b.(*Redis), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RedisConfig)(nil), (*openx.RedisConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RedisConfig_To_openx_RedisConfig(a.(*RedisConfig), b.(*openx.RedisConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.RedisConfig)(nil), (*RedisConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_RedisConfig_To_v1_RedisConfig(a.(*openx.RedisConfig), b.(*RedisConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RedisList)(nil), (*openx.RedisList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RedisList_To_openx_RedisList(a.(*RedisList), b.(*openx.RedisList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.RedisList)(nil), (*RedisList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_RedisList_To_v1_RedisList(a.(*openx.RedisList), b.(*RedisList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RedisSpec)(nil), (*openx.RedisSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RedisSpec_To_openx_RedisSpec(a.(*RedisSpec), b.(*openx.RedisSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.RedisSpec)(nil), (*RedisSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_RedisSpec_To_v1_RedisSpec(a.(*openx.RedisSpec), b.(*RedisSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Toleration)(nil), (*openx.Toleration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Toleration_To_openx_Toleration(a.(*Toleration), b.(*openx.Toleration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.Toleration)(nil), (*Toleration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_Toleration_To_v1_Toleration(a.(*openx.Toleration), b.(*Toleration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TolerationList)(nil), (*openx.TolerationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TolerationList_To_openx_TolerationList(a.(*TolerationList), b.(*openx.TolerationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.TolerationList)(nil), (*TolerationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_TolerationList_To_v1_TolerationList(a.(*openx.TolerationList), b.(*TolerationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TolerationSpec)(nil), (*openx.TolerationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TolerationSpec_To_openx_TolerationSpec(a.(*TolerationSpec), b.(*openx.TolerationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openx.TolerationSpec)(nil), (*TolerationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openx_TolerationSpec_To_v1_TolerationSpec(a.(*openx.TolerationSpec), b.(*TolerationSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_AccessControl_To_openx_AccessControl(in *AccessControl, out *openx.AccessControl, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_AccessControlSpec_To_openx_AccessControlSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_AccessControl_To_openx_AccessControl is an autogenerated conversion function.
func Convert_v1_AccessControl_To_openx_AccessControl(in *AccessControl, out *openx.AccessControl, s conversion.Scope) error {
	return autoConvert_v1_AccessControl_To_openx_AccessControl(in, out, s)
}

func autoConvert_openx_AccessControl_To_v1_AccessControl(in *openx.AccessControl, out *AccessControl, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_AccessControlSpec_To_v1_AccessControlSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_AccessControl_To_v1_AccessControl is an autogenerated conversion function.
func Convert_openx_AccessControl_To_v1_AccessControl(in *openx.AccessControl, out *AccessControl, s conversion.Scope) error {
	return autoConvert_openx_AccessControl_To_v1_AccessControl(in, out, s)
}

func autoConvert_v1_AccessControlList_To_openx_AccessControlList(in *AccessControlList, out *openx.AccessControlList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.AccessControl)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_AccessControlList_To_openx_AccessControlList is an autogenerated conversion function.
func Convert_v1_AccessControlList_To_openx_AccessControlList(in *AccessControlList, out *openx.AccessControlList, s conversion.Scope) error {
	return autoConvert_v1_AccessControlList_To_openx_AccessControlList(in, out, s)
}

func autoConvert_openx_AccessControlList_To_v1_AccessControlList(in *openx.AccessControlList, out *AccessControlList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]AccessControl)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_AccessControlList_To_v1_AccessControlList is an autogenerated conversion function.
func Convert_openx_AccessControlList_To_v1_AccessControlList(in *openx.AccessControlList, out *AccessControlList, s conversion.Scope) error {
	return autoConvert_openx_AccessControlList_To_v1_AccessControlList(in, out, s)
}

func autoConvert_v1_AccessControlSpec_To_openx_AccessControlSpec(in *AccessControlSpec, out *openx.AccessControlSpec, s conversion.Scope) error {
	if err := Convert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(&in.Instance, &out.Instance, s); err != nil {
		return err
	}
	if err := Convert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(&in.Status, &out.Status, s); err != nil {
		return err
	}
	if err := Convert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(&in.Type, &out.Type, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_AccessControlSpec_To_openx_AccessControlSpec is an autogenerated conversion function.
func Convert_v1_AccessControlSpec_To_openx_AccessControlSpec(in *AccessControlSpec, out *openx.AccessControlSpec, s conversion.Scope) error {
	return autoConvert_v1_AccessControlSpec_To_openx_AccessControlSpec(in, out, s)
}

func autoConvert_openx_AccessControlSpec_To_v1_AccessControlSpec(in *openx.AccessControlSpec, out *AccessControlSpec, s conversion.Scope) error {
	if err := Convert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(&in.Instance, &out.Instance, s); err != nil {
		return err
	}
	if err := Convert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(&in.Status, &out.Status, s); err != nil {
		return err
	}
	if err := Convert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(&in.Type, &out.Type, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_AccessControlSpec_To_v1_AccessControlSpec is an autogenerated conversion function.
func Convert_openx_AccessControlSpec_To_v1_AccessControlSpec(in *openx.AccessControlSpec, out *AccessControlSpec, s conversion.Scope) error {
	return autoConvert_openx_AccessControlSpec_To_v1_AccessControlSpec(in, out, s)
}

func autoConvert_v1_Affinity_To_openx_Affinity(in *Affinity, out *openx.Affinity, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_AffinitySpec_To_openx_AffinitySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Affinity_To_openx_Affinity is an autogenerated conversion function.
func Convert_v1_Affinity_To_openx_Affinity(in *Affinity, out *openx.Affinity, s conversion.Scope) error {
	return autoConvert_v1_Affinity_To_openx_Affinity(in, out, s)
}

func autoConvert_openx_Affinity_To_v1_Affinity(in *openx.Affinity, out *Affinity, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_AffinitySpec_To_v1_AffinitySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_Affinity_To_v1_Affinity is an autogenerated conversion function.
func Convert_openx_Affinity_To_v1_Affinity(in *openx.Affinity, out *Affinity, s conversion.Scope) error {
	return autoConvert_openx_Affinity_To_v1_Affinity(in, out, s)
}

func autoConvert_v1_AffinityList_To_openx_AffinityList(in *AffinityList, out *openx.AffinityList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.Affinity)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_AffinityList_To_openx_AffinityList is an autogenerated conversion function.
func Convert_v1_AffinityList_To_openx_AffinityList(in *AffinityList, out *openx.AffinityList, s conversion.Scope) error {
	return autoConvert_v1_AffinityList_To_openx_AffinityList(in, out, s)
}

func autoConvert_openx_AffinityList_To_v1_AffinityList(in *openx.AffinityList, out *AffinityList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Affinity)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_AffinityList_To_v1_AffinityList is an autogenerated conversion function.
func Convert_openx_AffinityList_To_v1_AffinityList(in *openx.AffinityList, out *AffinityList, s conversion.Scope) error {
	return autoConvert_openx_AffinityList_To_v1_AffinityList(in, out, s)
}

func autoConvert_v1_AffinitySpec_To_openx_AffinitySpec(in *AffinitySpec, out *openx.AffinitySpec, s conversion.Scope) error {
	out.Affinity = (*corev1.Affinity)(unsafe.Pointer(in.Affinity))
	return nil
}

// Convert_v1_AffinitySpec_To_openx_AffinitySpec is an autogenerated conversion function.
func Convert_v1_AffinitySpec_To_openx_AffinitySpec(in *AffinitySpec, out *openx.AffinitySpec, s conversion.Scope) error {
	return autoConvert_v1_AffinitySpec_To_openx_AffinitySpec(in, out, s)
}

func autoConvert_openx_AffinitySpec_To_v1_AffinitySpec(in *openx.AffinitySpec, out *AffinitySpec, s conversion.Scope) error {
	out.Affinity = (*corev1.Affinity)(unsafe.Pointer(in.Affinity))
	return nil
}

// Convert_openx_AffinitySpec_To_v1_AffinitySpec is an autogenerated conversion function.
func Convert_openx_AffinitySpec_To_v1_AffinitySpec(in *openx.AffinitySpec, out *AffinitySpec, s conversion.Scope) error {
	return autoConvert_openx_AffinitySpec_To_v1_AffinitySpec(in, out, s)
}

func autoConvert_v1_App_To_openx_App(in *App, out *openx.App, s conversion.Scope) error {
	out.AppName = in.AppName
	out.Pod = (*corev1.Pod)(unsafe.Pointer(in.Pod))
	out.Service = (*corev1.Service)(unsafe.Pointer(in.Service))
	if err := Convert_v1_PersistentStorage_To_openx_PersistentStorage(&in.PersistentStorage, &out.PersistentStorage, s); err != nil {
		return err
	}
	if err := Convert_v1_CloudNetworkConfig_To_openx_CloudNetworkConfig(&in.CloudNetworkConfig, &out.CloudNetworkConfig, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.WatchPolicy = openx.WatchPolicy(in.WatchPolicy)
	out.HorizontalPodAutoscalerSpec = (*v2.HorizontalPodAutoscalerSpec)(unsafe.Pointer(in.HorizontalPodAutoscalerSpec))
	out.ExtensionService = (*corev1.Service)(unsafe.Pointer(in.ExtensionService))
	return nil
}

// Convert_v1_App_To_openx_App is an autogenerated conversion function.
func Convert_v1_App_To_openx_App(in *App, out *openx.App, s conversion.Scope) error {
	return autoConvert_v1_App_To_openx_App(in, out, s)
}

func autoConvert_openx_App_To_v1_App(in *openx.App, out *App, s conversion.Scope) error {
	out.AppName = in.AppName
	out.Pod = (*corev1.Pod)(unsafe.Pointer(in.Pod))
	out.Service = (*corev1.Service)(unsafe.Pointer(in.Service))
	if err := Convert_openx_PersistentStorage_To_v1_PersistentStorage(&in.PersistentStorage, &out.PersistentStorage, s); err != nil {
		return err
	}
	if err := Convert_openx_CloudNetworkConfig_To_v1_CloudNetworkConfig(&in.CloudNetworkConfig, &out.CloudNetworkConfig, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.WatchPolicy = WatchPolicy(in.WatchPolicy)
	out.HorizontalPodAutoscalerSpec = (*v2.HorizontalPodAutoscalerSpec)(unsafe.Pointer(in.HorizontalPodAutoscalerSpec))
	out.ExtensionService = (*corev1.Service)(unsafe.Pointer(in.ExtensionService))
	return nil
}

// Convert_openx_App_To_v1_App is an autogenerated conversion function.
func Convert_openx_App_To_v1_App(in *openx.App, out *App, s conversion.Scope) error {
	return autoConvert_openx_App_To_v1_App(in, out, s)
}

func autoConvert_v1_AppStatus_To_openx_AppStatus(in *AppStatus, out *openx.AppStatus, s conversion.Scope) error {
	out.DeploymentStatus = in.DeploymentStatus
	out.HorizontalPodAutoscalerStatus = in.HorizontalPodAutoscalerStatus
	return nil
}

// Convert_v1_AppStatus_To_openx_AppStatus is an autogenerated conversion function.
func Convert_v1_AppStatus_To_openx_AppStatus(in *AppStatus, out *openx.AppStatus, s conversion.Scope) error {
	return autoConvert_v1_AppStatus_To_openx_AppStatus(in, out, s)
}

func autoConvert_openx_AppStatus_To_v1_AppStatus(in *openx.AppStatus, out *AppStatus, s conversion.Scope) error {
	out.DeploymentStatus = in.DeploymentStatus
	out.HorizontalPodAutoscalerStatus = in.HorizontalPodAutoscalerStatus
	return nil
}

// Convert_openx_AppStatus_To_v1_AppStatus is an autogenerated conversion function.
func Convert_openx_AppStatus_To_v1_AppStatus(in *openx.AppStatus, out *AppStatus, s conversion.Scope) error {
	return autoConvert_openx_AppStatus_To_v1_AppStatus(in, out, s)
}

func autoConvert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(in *CloudLoadBalancerObject, out *openx.CloudLoadBalancerObject, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = in.Value
	return nil
}

// Convert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject is an autogenerated conversion function.
func Convert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(in *CloudLoadBalancerObject, out *openx.CloudLoadBalancerObject, s conversion.Scope) error {
	return autoConvert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(in, out, s)
}

func autoConvert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(in *openx.CloudLoadBalancerObject, out *CloudLoadBalancerObject, s conversion.Scope) error {
	out.Key = in.Key
	out.Value = in.Value
	return nil
}

// Convert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject is an autogenerated conversion function.
func Convert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(in *openx.CloudLoadBalancerObject, out *CloudLoadBalancerObject, s conversion.Scope) error {
	return autoConvert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(in, out, s)
}

func autoConvert_v1_CloudNetworkConfig_To_openx_CloudNetworkConfig(in *CloudNetworkConfig, out *openx.CloudNetworkConfig, s conversion.Scope) error {
	out.CloudSLB = (*openx.CloudSLB)(unsafe.Pointer(in.CloudSLB))
	return nil
}

// Convert_v1_CloudNetworkConfig_To_openx_CloudNetworkConfig is an autogenerated conversion function.
func Convert_v1_CloudNetworkConfig_To_openx_CloudNetworkConfig(in *CloudNetworkConfig, out *openx.CloudNetworkConfig, s conversion.Scope) error {
	return autoConvert_v1_CloudNetworkConfig_To_openx_CloudNetworkConfig(in, out, s)
}

func autoConvert_openx_CloudNetworkConfig_To_v1_CloudNetworkConfig(in *openx.CloudNetworkConfig, out *CloudNetworkConfig, s conversion.Scope) error {
	out.CloudSLB = (*CloudSLB)(unsafe.Pointer(in.CloudSLB))
	return nil
}

// Convert_openx_CloudNetworkConfig_To_v1_CloudNetworkConfig is an autogenerated conversion function.
func Convert_openx_CloudNetworkConfig_To_v1_CloudNetworkConfig(in *openx.CloudNetworkConfig, out *CloudNetworkConfig, s conversion.Scope) error {
	return autoConvert_openx_CloudNetworkConfig_To_v1_CloudNetworkConfig(in, out, s)
}

func autoConvert_v1_CloudSLB_To_openx_CloudSLB(in *CloudSLB, out *openx.CloudSLB, s conversion.Scope) error {
	out.LoadBalancerId = in.LoadBalancerId
	out.OverrideListeners = in.OverrideListeners
	out.Status = openx.CloudLoadBalancerStatus(in.Status)
	out.AccessControlId = in.AccessControlId
	return nil
}

// Convert_v1_CloudSLB_To_openx_CloudSLB is an autogenerated conversion function.
func Convert_v1_CloudSLB_To_openx_CloudSLB(in *CloudSLB, out *openx.CloudSLB, s conversion.Scope) error {
	return autoConvert_v1_CloudSLB_To_openx_CloudSLB(in, out, s)
}

func autoConvert_openx_CloudSLB_To_v1_CloudSLB(in *openx.CloudSLB, out *CloudSLB, s conversion.Scope) error {
	out.LoadBalancerId = in.LoadBalancerId
	out.OverrideListeners = in.OverrideListeners
	out.Status = CloudLoadBalancerStatus(in.Status)
	out.AccessControlId = in.AccessControlId
	return nil
}

// Convert_openx_CloudSLB_To_v1_CloudSLB is an autogenerated conversion function.
func Convert_openx_CloudSLB_To_v1_CloudSLB(in *openx.CloudSLB, out *CloudSLB, s conversion.Scope) error {
	return autoConvert_openx_CloudSLB_To_v1_CloudSLB(in, out, s)
}

func autoConvert_v1_ClusterStatus_To_openx_ClusterStatus(in *ClusterStatus, out *openx.ClusterStatus, s conversion.Scope) error {
	out.Master = in.Master
	out.Slave = in.Slave
	return nil
}

// Convert_v1_ClusterStatus_To_openx_ClusterStatus is an autogenerated conversion function.
func Convert_v1_ClusterStatus_To_openx_ClusterStatus(in *ClusterStatus, out *openx.ClusterStatus, s conversion.Scope) error {
	return autoConvert_v1_ClusterStatus_To_openx_ClusterStatus(in, out, s)
}

func autoConvert_openx_ClusterStatus_To_v1_ClusterStatus(in *openx.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	out.Master = in.Master
	out.Slave = in.Slave
	return nil
}

// Convert_openx_ClusterStatus_To_v1_ClusterStatus is an autogenerated conversion function.
func Convert_openx_ClusterStatus_To_v1_ClusterStatus(in *openx.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return autoConvert_openx_ClusterStatus_To_v1_ClusterStatus(in, out, s)
}

func autoConvert_v1_Etcd_To_openx_Etcd(in *Etcd, out *openx.Etcd, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_EtcdSpec_To_openx_EtcdSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_v1_Etcd_To_openx_Etcd is an autogenerated conversion function.
func Convert_v1_Etcd_To_openx_Etcd(in *Etcd, out *openx.Etcd, s conversion.Scope) error {
	return autoConvert_v1_Etcd_To_openx_Etcd(in, out, s)
}

func autoConvert_openx_Etcd_To_v1_Etcd(in *openx.Etcd, out *Etcd, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_EtcdSpec_To_v1_EtcdSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_openx_Etcd_To_v1_Etcd is an autogenerated conversion function.
func Convert_openx_Etcd_To_v1_Etcd(in *openx.Etcd, out *Etcd, s conversion.Scope) error {
	return autoConvert_openx_Etcd_To_v1_Etcd(in, out, s)
}

func autoConvert_v1_EtcdList_To_openx_EtcdList(in *EtcdList, out *openx.EtcdList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.Etcd)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_EtcdList_To_openx_EtcdList is an autogenerated conversion function.
func Convert_v1_EtcdList_To_openx_EtcdList(in *EtcdList, out *openx.EtcdList, s conversion.Scope) error {
	return autoConvert_v1_EtcdList_To_openx_EtcdList(in, out, s)
}

func autoConvert_openx_EtcdList_To_v1_EtcdList(in *openx.EtcdList, out *EtcdList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Etcd)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_EtcdList_To_v1_EtcdList is an autogenerated conversion function.
func Convert_openx_EtcdList_To_v1_EtcdList(in *openx.EtcdList, out *EtcdList, s conversion.Scope) error {
	return autoConvert_openx_EtcdList_To_v1_EtcdList(in, out, s)
}

func autoConvert_v1_EtcdSpec_To_openx_EtcdSpec(in *EtcdSpec, out *openx.EtcdSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	if err := Convert_v1_PersistentStorage_To_openx_PersistentStorage(&in.PersistentStorage, &out.PersistentStorage, s); err != nil {
		return err
	}
	out.Pod = (*corev1.Pod)(unsafe.Pointer(in.Pod))
	return nil
}

// Convert_v1_EtcdSpec_To_openx_EtcdSpec is an autogenerated conversion function.
func Convert_v1_EtcdSpec_To_openx_EtcdSpec(in *EtcdSpec, out *openx.EtcdSpec, s conversion.Scope) error {
	return autoConvert_v1_EtcdSpec_To_openx_EtcdSpec(in, out, s)
}

func autoConvert_openx_EtcdSpec_To_v1_EtcdSpec(in *openx.EtcdSpec, out *EtcdSpec, s conversion.Scope) error {
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	if err := Convert_openx_PersistentStorage_To_v1_PersistentStorage(&in.PersistentStorage, &out.PersistentStorage, s); err != nil {
		return err
	}
	out.Pod = (*corev1.Pod)(unsafe.Pointer(in.Pod))
	return nil
}

// Convert_openx_EtcdSpec_To_v1_EtcdSpec is an autogenerated conversion function.
func Convert_openx_EtcdSpec_To_v1_EtcdSpec(in *openx.EtcdSpec, out *EtcdSpec, s conversion.Scope) error {
	return autoConvert_openx_EtcdSpec_To_v1_EtcdSpec(in, out, s)
}

func autoConvert_v1_LoadBalancer_To_openx_LoadBalancer(in *LoadBalancer, out *openx.LoadBalancer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_LoadBalancerSpec_To_openx_LoadBalancerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_LoadBalancer_To_openx_LoadBalancer is an autogenerated conversion function.
func Convert_v1_LoadBalancer_To_openx_LoadBalancer(in *LoadBalancer, out *openx.LoadBalancer, s conversion.Scope) error {
	return autoConvert_v1_LoadBalancer_To_openx_LoadBalancer(in, out, s)
}

func autoConvert_openx_LoadBalancer_To_v1_LoadBalancer(in *openx.LoadBalancer, out *LoadBalancer, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_LoadBalancerSpec_To_v1_LoadBalancerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_LoadBalancer_To_v1_LoadBalancer is an autogenerated conversion function.
func Convert_openx_LoadBalancer_To_v1_LoadBalancer(in *openx.LoadBalancer, out *LoadBalancer, s conversion.Scope) error {
	return autoConvert_openx_LoadBalancer_To_v1_LoadBalancer(in, out, s)
}

func autoConvert_v1_LoadBalancerList_To_openx_LoadBalancerList(in *LoadBalancerList, out *openx.LoadBalancerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.LoadBalancer)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_LoadBalancerList_To_openx_LoadBalancerList is an autogenerated conversion function.
func Convert_v1_LoadBalancerList_To_openx_LoadBalancerList(in *LoadBalancerList, out *openx.LoadBalancerList, s conversion.Scope) error {
	return autoConvert_v1_LoadBalancerList_To_openx_LoadBalancerList(in, out, s)
}

func autoConvert_openx_LoadBalancerList_To_v1_LoadBalancerList(in *openx.LoadBalancerList, out *LoadBalancerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]LoadBalancer)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_LoadBalancerList_To_v1_LoadBalancerList is an autogenerated conversion function.
func Convert_openx_LoadBalancerList_To_v1_LoadBalancerList(in *openx.LoadBalancerList, out *LoadBalancerList, s conversion.Scope) error {
	return autoConvert_openx_LoadBalancerList_To_v1_LoadBalancerList(in, out, s)
}

func autoConvert_v1_LoadBalancerSpec_To_openx_LoadBalancerSpec(in *LoadBalancerSpec, out *openx.LoadBalancerSpec, s conversion.Scope) error {
	if err := Convert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(&in.Instance, &out.Instance, s); err != nil {
		return err
	}
	if err := Convert_v1_CloudLoadBalancerObject_To_openx_CloudLoadBalancerObject(&in.OverrideListeners, &out.OverrideListeners, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_LoadBalancerSpec_To_openx_LoadBalancerSpec is an autogenerated conversion function.
func Convert_v1_LoadBalancerSpec_To_openx_LoadBalancerSpec(in *LoadBalancerSpec, out *openx.LoadBalancerSpec, s conversion.Scope) error {
	return autoConvert_v1_LoadBalancerSpec_To_openx_LoadBalancerSpec(in, out, s)
}

func autoConvert_openx_LoadBalancerSpec_To_v1_LoadBalancerSpec(in *openx.LoadBalancerSpec, out *LoadBalancerSpec, s conversion.Scope) error {
	if err := Convert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(&in.Instance, &out.Instance, s); err != nil {
		return err
	}
	if err := Convert_openx_CloudLoadBalancerObject_To_v1_CloudLoadBalancerObject(&in.OverrideListeners, &out.OverrideListeners, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_LoadBalancerSpec_To_v1_LoadBalancerSpec is an autogenerated conversion function.
func Convert_openx_LoadBalancerSpec_To_v1_LoadBalancerSpec(in *openx.LoadBalancerSpec, out *LoadBalancerSpec, s conversion.Scope) error {
	return autoConvert_openx_LoadBalancerSpec_To_v1_LoadBalancerSpec(in, out, s)
}

func autoConvert_v1_Mysql_To_openx_Mysql(in *Mysql, out *openx.Mysql, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_MysqlSpec_To_openx_MysqlSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ClusterStatus_To_openx_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Mysql_To_openx_Mysql is an autogenerated conversion function.
func Convert_v1_Mysql_To_openx_Mysql(in *Mysql, out *openx.Mysql, s conversion.Scope) error {
	return autoConvert_v1_Mysql_To_openx_Mysql(in, out, s)
}

func autoConvert_openx_Mysql_To_v1_Mysql(in *openx.Mysql, out *Mysql, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_MysqlSpec_To_v1_MysqlSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_openx_ClusterStatus_To_v1_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_Mysql_To_v1_Mysql is an autogenerated conversion function.
func Convert_openx_Mysql_To_v1_Mysql(in *openx.Mysql, out *Mysql, s conversion.Scope) error {
	return autoConvert_openx_Mysql_To_v1_Mysql(in, out, s)
}

func autoConvert_v1_MysqlConfig_To_openx_MysqlConfig(in *MysqlConfig, out *openx.MysqlConfig, s conversion.Scope) error {
	out.Role = openx.ClusterRole(in.Role)
	if err := Convert_v1_MysqlServerConfig_To_openx_MysqlServerConfig(&in.MysqlServerConfig, &out.MysqlServerConfig, s); err != nil {
		return err
	}
	out.Pod = (*corev1.Pod)(unsafe.Pointer(in.Pod))
	out.Service = (*corev1.Service)(unsafe.Pointer(in.Service))
	if err := Convert_v1_PersistentStorage_To_openx_PersistentStorage(&in.PersistentStorage, &out.PersistentStorage, s); err != nil {
		return err
	}
	if err := Convert_v1_CloudNetworkConfig_To_openx_CloudNetworkConfig(&in.CloudNetworkConfig, &out.CloudNetworkConfig, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

// Convert_v1_MysqlConfig_To_openx_MysqlConfig is an autogenerated conversion function.
func Convert_v1_MysqlConfig_To_openx_MysqlConfig(in *MysqlConfig, out *openx.MysqlConfig, s conversion.Scope) error {
	return autoConvert_v1_MysqlConfig_To_openx_MysqlConfig(in, out, s)
}

func autoConvert_openx_MysqlConfig_To_v1_MysqlConfig(in *openx.MysqlConfig, out *MysqlConfig, s conversion.Scope) error {
	out.Role = ClusterRole(in.Role)
	if err := Convert_openx_MysqlServerConfig_To_v1_MysqlServerConfig(&in.MysqlServerConfig, &out.MysqlServerConfig, s); err != nil {
		return err
	}
	out.Pod = (*corev1.Pod)(unsafe.Pointer(in.Pod))
	out.Service = (*corev1.Service)(unsafe.Pointer(in.Service))
	if err := Convert_openx_PersistentStorage_To_v1_PersistentStorage(&in.PersistentStorage, &out.PersistentStorage, s); err != nil {
		return err
	}
	if err := Convert_openx_CloudNetworkConfig_To_v1_CloudNetworkConfig(&in.CloudNetworkConfig, &out.CloudNetworkConfig, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

// Convert_openx_MysqlConfig_To_v1_MysqlConfig is an autogenerated conversion function.
func Convert_openx_MysqlConfig_To_v1_MysqlConfig(in *openx.MysqlConfig, out *MysqlConfig, s conversion.Scope) error {
	return autoConvert_openx_MysqlConfig_To_v1_MysqlConfig(in, out, s)
}

func autoConvert_v1_MysqlList_To_openx_MysqlList(in *MysqlList, out *openx.MysqlList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.Mysql)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_MysqlList_To_openx_MysqlList is an autogenerated conversion function.
func Convert_v1_MysqlList_To_openx_MysqlList(in *MysqlList, out *openx.MysqlList, s conversion.Scope) error {
	return autoConvert_v1_MysqlList_To_openx_MysqlList(in, out, s)
}

func autoConvert_openx_MysqlList_To_v1_MysqlList(in *openx.MysqlList, out *MysqlList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Mysql)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_MysqlList_To_v1_MysqlList is an autogenerated conversion function.
func Convert_openx_MysqlList_To_v1_MysqlList(in *openx.MysqlList, out *MysqlList, s conversion.Scope) error {
	return autoConvert_openx_MysqlList_To_v1_MysqlList(in, out, s)
}

func autoConvert_v1_MysqlServerConfig_To_openx_MysqlServerConfig(in *MysqlServerConfig, out *openx.MysqlServerConfig, s conversion.Scope) error {
	out.ServerId = (*int32)(unsafe.Pointer(in.ServerId))
	out.Host = in.Host
	out.User = in.User
	out.Password = in.Password
	out.LogFile = in.LogFile
	out.LogPosition = in.LogPosition
	return nil
}

// Convert_v1_MysqlServerConfig_To_openx_MysqlServerConfig is an autogenerated conversion function.
func Convert_v1_MysqlServerConfig_To_openx_MysqlServerConfig(in *MysqlServerConfig, out *openx.MysqlServerConfig, s conversion.Scope) error {
	return autoConvert_v1_MysqlServerConfig_To_openx_MysqlServerConfig(in, out, s)
}

func autoConvert_openx_MysqlServerConfig_To_v1_MysqlServerConfig(in *openx.MysqlServerConfig, out *MysqlServerConfig, s conversion.Scope) error {
	out.ServerId = (*int32)(unsafe.Pointer(in.ServerId))
	out.Host = in.Host
	out.User = in.User
	out.Password = in.Password
	out.LogFile = in.LogFile
	out.LogPosition = in.LogPosition
	return nil
}

// Convert_openx_MysqlServerConfig_To_v1_MysqlServerConfig is an autogenerated conversion function.
func Convert_openx_MysqlServerConfig_To_v1_MysqlServerConfig(in *openx.MysqlServerConfig, out *MysqlServerConfig, s conversion.Scope) error {
	return autoConvert_openx_MysqlServerConfig_To_v1_MysqlServerConfig(in, out, s)
}

func autoConvert_v1_MysqlSpec_To_openx_MysqlSpec(in *MysqlSpec, out *openx.MysqlSpec, s conversion.Scope) error {
	if err := Convert_v1_MysqlConfig_To_openx_MysqlConfig(&in.Master, &out.Master, s); err != nil {
		return err
	}
	if err := Convert_v1_MysqlConfig_To_openx_MysqlConfig(&in.Slave, &out.Slave, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_MysqlSpec_To_openx_MysqlSpec is an autogenerated conversion function.
func Convert_v1_MysqlSpec_To_openx_MysqlSpec(in *MysqlSpec, out *openx.MysqlSpec, s conversion.Scope) error {
	return autoConvert_v1_MysqlSpec_To_openx_MysqlSpec(in, out, s)
}

func autoConvert_openx_MysqlSpec_To_v1_MysqlSpec(in *openx.MysqlSpec, out *MysqlSpec, s conversion.Scope) error {
	if err := Convert_openx_MysqlConfig_To_v1_MysqlConfig(&in.Master, &out.Master, s); err != nil {
		return err
	}
	if err := Convert_openx_MysqlConfig_To_v1_MysqlConfig(&in.Slave, &out.Slave, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_MysqlSpec_To_v1_MysqlSpec is an autogenerated conversion function.
func Convert_openx_MysqlSpec_To_v1_MysqlSpec(in *openx.MysqlSpec, out *MysqlSpec, s conversion.Scope) error {
	return autoConvert_openx_MysqlSpec_To_v1_MysqlSpec(in, out, s)
}

func autoConvert_v1_NodeSelector_To_openx_NodeSelector(in *NodeSelector, out *openx.NodeSelector, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_NodeSelectorSpec_To_openx_NodeSelectorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_NodeSelector_To_openx_NodeSelector is an autogenerated conversion function.
func Convert_v1_NodeSelector_To_openx_NodeSelector(in *NodeSelector, out *openx.NodeSelector, s conversion.Scope) error {
	return autoConvert_v1_NodeSelector_To_openx_NodeSelector(in, out, s)
}

func autoConvert_openx_NodeSelector_To_v1_NodeSelector(in *openx.NodeSelector, out *NodeSelector, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_NodeSelectorSpec_To_v1_NodeSelectorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_NodeSelector_To_v1_NodeSelector is an autogenerated conversion function.
func Convert_openx_NodeSelector_To_v1_NodeSelector(in *openx.NodeSelector, out *NodeSelector, s conversion.Scope) error {
	return autoConvert_openx_NodeSelector_To_v1_NodeSelector(in, out, s)
}

func autoConvert_v1_NodeSelectorList_To_openx_NodeSelectorList(in *NodeSelectorList, out *openx.NodeSelectorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.NodeSelector)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_NodeSelectorList_To_openx_NodeSelectorList is an autogenerated conversion function.
func Convert_v1_NodeSelectorList_To_openx_NodeSelectorList(in *NodeSelectorList, out *openx.NodeSelectorList, s conversion.Scope) error {
	return autoConvert_v1_NodeSelectorList_To_openx_NodeSelectorList(in, out, s)
}

func autoConvert_openx_NodeSelectorList_To_v1_NodeSelectorList(in *openx.NodeSelectorList, out *NodeSelectorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NodeSelector)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_NodeSelectorList_To_v1_NodeSelectorList is an autogenerated conversion function.
func Convert_openx_NodeSelectorList_To_v1_NodeSelectorList(in *openx.NodeSelectorList, out *NodeSelectorList, s conversion.Scope) error {
	return autoConvert_openx_NodeSelectorList_To_v1_NodeSelectorList(in, out, s)
}

func autoConvert_v1_NodeSelectorSpec_To_openx_NodeSelectorSpec(in *NodeSelectorSpec, out *openx.NodeSelectorSpec, s conversion.Scope) error {
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	return nil
}

// Convert_v1_NodeSelectorSpec_To_openx_NodeSelectorSpec is an autogenerated conversion function.
func Convert_v1_NodeSelectorSpec_To_openx_NodeSelectorSpec(in *NodeSelectorSpec, out *openx.NodeSelectorSpec, s conversion.Scope) error {
	return autoConvert_v1_NodeSelectorSpec_To_openx_NodeSelectorSpec(in, out, s)
}

func autoConvert_openx_NodeSelectorSpec_To_v1_NodeSelectorSpec(in *openx.NodeSelectorSpec, out *NodeSelectorSpec, s conversion.Scope) error {
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	return nil
}

// Convert_openx_NodeSelectorSpec_To_v1_NodeSelectorSpec is an autogenerated conversion function.
func Convert_openx_NodeSelectorSpec_To_v1_NodeSelectorSpec(in *openx.NodeSelectorSpec, out *NodeSelectorSpec, s conversion.Scope) error {
	return autoConvert_openx_NodeSelectorSpec_To_v1_NodeSelectorSpec(in, out, s)
}

func autoConvert_v1_Openx_To_openx_Openx(in *Openx, out *openx.Openx, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_OpenxSpec_To_openx_OpenxSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_OpenxStatus_To_openx_OpenxStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Openx_To_openx_Openx is an autogenerated conversion function.
func Convert_v1_Openx_To_openx_Openx(in *Openx, out *openx.Openx, s conversion.Scope) error {
	return autoConvert_v1_Openx_To_openx_Openx(in, out, s)
}

func autoConvert_openx_Openx_To_v1_Openx(in *openx.Openx, out *Openx, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_OpenxSpec_To_v1_OpenxSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_openx_OpenxStatus_To_v1_OpenxStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_Openx_To_v1_Openx is an autogenerated conversion function.
func Convert_openx_Openx_To_v1_Openx(in *openx.Openx, out *Openx, s conversion.Scope) error {
	return autoConvert_openx_Openx_To_v1_Openx(in, out, s)
}

func autoConvert_v1_OpenxList_To_openx_OpenxList(in *OpenxList, out *openx.OpenxList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.Openx)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OpenxList_To_openx_OpenxList is an autogenerated conversion function.
func Convert_v1_OpenxList_To_openx_OpenxList(in *OpenxList, out *openx.OpenxList, s conversion.Scope) error {
	return autoConvert_v1_OpenxList_To_openx_OpenxList(in, out, s)
}

func autoConvert_openx_OpenxList_To_v1_OpenxList(in *openx.OpenxList, out *OpenxList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Openx)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_OpenxList_To_v1_OpenxList is an autogenerated conversion function.
func Convert_openx_OpenxList_To_v1_OpenxList(in *openx.OpenxList, out *OpenxList, s conversion.Scope) error {
	return autoConvert_openx_OpenxList_To_v1_OpenxList(in, out, s)
}

func autoConvert_v1_OpenxSpec_To_openx_OpenxSpec(in *OpenxSpec, out *openx.OpenxSpec, s conversion.Scope) error {
	out.Applications = *(*[]openx.App)(unsafe.Pointer(&in.Applications))
	return nil
}

// Convert_v1_OpenxSpec_To_openx_OpenxSpec is an autogenerated conversion function.
func Convert_v1_OpenxSpec_To_openx_OpenxSpec(in *OpenxSpec, out *openx.OpenxSpec, s conversion.Scope) error {
	return autoConvert_v1_OpenxSpec_To_openx_OpenxSpec(in, out, s)
}

func autoConvert_openx_OpenxSpec_To_v1_OpenxSpec(in *openx.OpenxSpec, out *OpenxSpec, s conversion.Scope) error {
	out.Applications = *(*[]App)(unsafe.Pointer(&in.Applications))
	return nil
}

// Convert_openx_OpenxSpec_To_v1_OpenxSpec is an autogenerated conversion function.
func Convert_openx_OpenxSpec_To_v1_OpenxSpec(in *openx.OpenxSpec, out *OpenxSpec, s conversion.Scope) error {
	return autoConvert_openx_OpenxSpec_To_v1_OpenxSpec(in, out, s)
}

func autoConvert_v1_OpenxStatus_To_openx_OpenxStatus(in *OpenxStatus, out *openx.OpenxStatus, s conversion.Scope) error {
	out.Items = *(*map[string]openx.AppStatus)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OpenxStatus_To_openx_OpenxStatus is an autogenerated conversion function.
func Convert_v1_OpenxStatus_To_openx_OpenxStatus(in *OpenxStatus, out *openx.OpenxStatus, s conversion.Scope) error {
	return autoConvert_v1_OpenxStatus_To_openx_OpenxStatus(in, out, s)
}

func autoConvert_openx_OpenxStatus_To_v1_OpenxStatus(in *openx.OpenxStatus, out *OpenxStatus, s conversion.Scope) error {
	out.Items = *(*map[string]AppStatus)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_OpenxStatus_To_v1_OpenxStatus is an autogenerated conversion function.
func Convert_openx_OpenxStatus_To_v1_OpenxStatus(in *openx.OpenxStatus, out *OpenxStatus, s conversion.Scope) error {
	return autoConvert_openx_OpenxStatus_To_v1_OpenxStatus(in, out, s)
}

func autoConvert_v1_PersistentStorage_To_openx_PersistentStorage(in *PersistentStorage, out *openx.PersistentStorage, s conversion.Scope) error {
	out.StorageVolumePath = in.StorageVolumePath
	return nil
}

// Convert_v1_PersistentStorage_To_openx_PersistentStorage is an autogenerated conversion function.
func Convert_v1_PersistentStorage_To_openx_PersistentStorage(in *PersistentStorage, out *openx.PersistentStorage, s conversion.Scope) error {
	return autoConvert_v1_PersistentStorage_To_openx_PersistentStorage(in, out, s)
}

func autoConvert_openx_PersistentStorage_To_v1_PersistentStorage(in *openx.PersistentStorage, out *PersistentStorage, s conversion.Scope) error {
	out.StorageVolumePath = in.StorageVolumePath
	return nil
}

// Convert_openx_PersistentStorage_To_v1_PersistentStorage is an autogenerated conversion function.
func Convert_openx_PersistentStorage_To_v1_PersistentStorage(in *openx.PersistentStorage, out *PersistentStorage, s conversion.Scope) error {
	return autoConvert_openx_PersistentStorage_To_v1_PersistentStorage(in, out, s)
}

func autoConvert_v1_Redis_To_openx_Redis(in *Redis, out *openx.Redis, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_RedisSpec_To_openx_RedisSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_ClusterStatus_To_openx_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Redis_To_openx_Redis is an autogenerated conversion function.
func Convert_v1_Redis_To_openx_Redis(in *Redis, out *openx.Redis, s conversion.Scope) error {
	return autoConvert_v1_Redis_To_openx_Redis(in, out, s)
}

func autoConvert_openx_Redis_To_v1_Redis(in *openx.Redis, out *Redis, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_RedisSpec_To_v1_RedisSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_openx_ClusterStatus_To_v1_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_Redis_To_v1_Redis is an autogenerated conversion function.
func Convert_openx_Redis_To_v1_Redis(in *openx.Redis, out *Redis, s conversion.Scope) error {
	return autoConvert_openx_Redis_To_v1_Redis(in, out, s)
}

func autoConvert_v1_RedisConfig_To_openx_RedisConfig(in *RedisConfig, out *openx.RedisConfig, s conversion.Scope) error {
	out.Role = openx.ClusterRole(in.Role)
	out.Pod = (*corev1.Pod)(unsafe.Pointer(in.Pod))
	out.Service = (*corev1.Service)(unsafe.Pointer(in.Service))
	if err := Convert_v1_PersistentStorage_To_openx_PersistentStorage(&in.PersistentStorage, &out.PersistentStorage, s); err != nil {
		return err
	}
	if err := Convert_v1_CloudNetworkConfig_To_openx_CloudNetworkConfig(&in.CloudNetworkConfig, &out.CloudNetworkConfig, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

// Convert_v1_RedisConfig_To_openx_RedisConfig is an autogenerated conversion function.
func Convert_v1_RedisConfig_To_openx_RedisConfig(in *RedisConfig, out *openx.RedisConfig, s conversion.Scope) error {
	return autoConvert_v1_RedisConfig_To_openx_RedisConfig(in, out, s)
}

func autoConvert_openx_RedisConfig_To_v1_RedisConfig(in *openx.RedisConfig, out *RedisConfig, s conversion.Scope) error {
	out.Role = ClusterRole(in.Role)
	out.Pod = (*corev1.Pod)(unsafe.Pointer(in.Pod))
	out.Service = (*corev1.Service)(unsafe.Pointer(in.Service))
	if err := Convert_openx_PersistentStorage_To_v1_PersistentStorage(&in.PersistentStorage, &out.PersistentStorage, s); err != nil {
		return err
	}
	if err := Convert_openx_CloudNetworkConfig_To_v1_CloudNetworkConfig(&in.CloudNetworkConfig, &out.CloudNetworkConfig, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	return nil
}

// Convert_openx_RedisConfig_To_v1_RedisConfig is an autogenerated conversion function.
func Convert_openx_RedisConfig_To_v1_RedisConfig(in *openx.RedisConfig, out *RedisConfig, s conversion.Scope) error {
	return autoConvert_openx_RedisConfig_To_v1_RedisConfig(in, out, s)
}

func autoConvert_v1_RedisList_To_openx_RedisList(in *RedisList, out *openx.RedisList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.Redis)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_RedisList_To_openx_RedisList is an autogenerated conversion function.
func Convert_v1_RedisList_To_openx_RedisList(in *RedisList, out *openx.RedisList, s conversion.Scope) error {
	return autoConvert_v1_RedisList_To_openx_RedisList(in, out, s)
}

func autoConvert_openx_RedisList_To_v1_RedisList(in *openx.RedisList, out *RedisList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Redis)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_RedisList_To_v1_RedisList is an autogenerated conversion function.
func Convert_openx_RedisList_To_v1_RedisList(in *openx.RedisList, out *RedisList, s conversion.Scope) error {
	return autoConvert_openx_RedisList_To_v1_RedisList(in, out, s)
}

func autoConvert_v1_RedisSpec_To_openx_RedisSpec(in *RedisSpec, out *openx.RedisSpec, s conversion.Scope) error {
	if err := Convert_v1_RedisConfig_To_openx_RedisConfig(&in.Master, &out.Master, s); err != nil {
		return err
	}
	if err := Convert_v1_RedisConfig_To_openx_RedisConfig(&in.Slave, &out.Slave, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_RedisSpec_To_openx_RedisSpec is an autogenerated conversion function.
func Convert_v1_RedisSpec_To_openx_RedisSpec(in *RedisSpec, out *openx.RedisSpec, s conversion.Scope) error {
	return autoConvert_v1_RedisSpec_To_openx_RedisSpec(in, out, s)
}

func autoConvert_openx_RedisSpec_To_v1_RedisSpec(in *openx.RedisSpec, out *RedisSpec, s conversion.Scope) error {
	if err := Convert_openx_RedisConfig_To_v1_RedisConfig(&in.Master, &out.Master, s); err != nil {
		return err
	}
	if err := Convert_openx_RedisConfig_To_v1_RedisConfig(&in.Slave, &out.Slave, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_RedisSpec_To_v1_RedisSpec is an autogenerated conversion function.
func Convert_openx_RedisSpec_To_v1_RedisSpec(in *openx.RedisSpec, out *RedisSpec, s conversion.Scope) error {
	return autoConvert_openx_RedisSpec_To_v1_RedisSpec(in, out, s)
}

func autoConvert_v1_Toleration_To_openx_Toleration(in *Toleration, out *openx.Toleration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_TolerationSpec_To_openx_TolerationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Toleration_To_openx_Toleration is an autogenerated conversion function.
func Convert_v1_Toleration_To_openx_Toleration(in *Toleration, out *openx.Toleration, s conversion.Scope) error {
	return autoConvert_v1_Toleration_To_openx_Toleration(in, out, s)
}

func autoConvert_openx_Toleration_To_v1_Toleration(in *openx.Toleration, out *Toleration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openx_TolerationSpec_To_v1_TolerationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_openx_Toleration_To_v1_Toleration is an autogenerated conversion function.
func Convert_openx_Toleration_To_v1_Toleration(in *openx.Toleration, out *Toleration, s conversion.Scope) error {
	return autoConvert_openx_Toleration_To_v1_Toleration(in, out, s)
}

func autoConvert_v1_TolerationList_To_openx_TolerationList(in *TolerationList, out *openx.TolerationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openx.Toleration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_TolerationList_To_openx_TolerationList is an autogenerated conversion function.
func Convert_v1_TolerationList_To_openx_TolerationList(in *TolerationList, out *openx.TolerationList, s conversion.Scope) error {
	return autoConvert_v1_TolerationList_To_openx_TolerationList(in, out, s)
}

func autoConvert_openx_TolerationList_To_v1_TolerationList(in *openx.TolerationList, out *TolerationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Toleration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openx_TolerationList_To_v1_TolerationList is an autogenerated conversion function.
func Convert_openx_TolerationList_To_v1_TolerationList(in *openx.TolerationList, out *TolerationList, s conversion.Scope) error {
	return autoConvert_openx_TolerationList_To_v1_TolerationList(in, out, s)
}

func autoConvert_v1_TolerationSpec_To_openx_TolerationSpec(in *TolerationSpec, out *openx.TolerationSpec, s conversion.Scope) error {
	out.Toleration = in.Toleration
	return nil
}

// Convert_v1_TolerationSpec_To_openx_TolerationSpec is an autogenerated conversion function.
func Convert_v1_TolerationSpec_To_openx_TolerationSpec(in *TolerationSpec, out *openx.TolerationSpec, s conversion.Scope) error {
	return autoConvert_v1_TolerationSpec_To_openx_TolerationSpec(in, out, s)
}

func autoConvert_openx_TolerationSpec_To_v1_TolerationSpec(in *openx.TolerationSpec, out *TolerationSpec, s conversion.Scope) error {
	out.Toleration = in.Toleration
	return nil
}

// Convert_openx_TolerationSpec_To_v1_TolerationSpec is an autogenerated conversion function.
func Convert_openx_TolerationSpec_To_v1_TolerationSpec(in *openx.TolerationSpec, out *TolerationSpec, s conversion.Scope) error {
	return autoConvert_openx_TolerationSpec_To_v1_TolerationSpec(in, out, s)
}
